option('anthy',
       type: 'feature',
       value: 'auto',
       description: 'build a plugin for Anthy (EUC-JP)')
option('anthy_static',
       type: 'boolean',
       value: false,
       description: 'build Anthy (EUC-JP) into libuim instead of a plugin')
option('anthy_utf8',
       type: 'feature',
       value: 'disabled',
       description: 'build a plugin for Anthy (UTF-8)')
option('anthy_utf8_static',
       type: 'boolean',
       value: false,
       description: 'build Anthy (UTF-8) into libuim instead of a plugin')
option('expat',
       type: 'feature',
       value: 'disabled',
       description: 'build a plugin for Expat')
option('ffi',
       type: 'feature',
       value: 'disabled',
       description: 'build a plugin for libffi')
option('libedit',
       type: 'feature',
       value: 'auto',
       description: 'build a plugin for libedit used by uim-sh')
option('m17nlib',
       type: 'feature',
       value: 'auto',
       description: 'build a plugin for m17n-lib')
option('openssl',
       type: 'feature',
       value: 'disabled',
       description: 'build a plugin for OpenSSL')
option('skk',
       type: 'boolean',
       value: true,
       description: 'build a plugin for SKK')
option('sqlite3',
       type: 'feature',
       value: 'auto',
       description: 'build a plugin for SQLite3')
