EXTRA_DIST = \
	00INDEX \
	COMPATIBILITY \
	CUSTOM \
	DOT-UIM \
	ENV \
	HELPER-CANDWIN \
	HELPER-PROTOCOL \
	KEY \
	PACKAGING \
	PLUGIN \
	RELEASING \
	UIM-SCM \
	UIM-SH \
	UNIT-TEST \
	skk-utf8-migration-guide-ja.md \
	skk-utf8-migration-guide.md \
	uim-custom-cli.md \
	uim-im-switcher-cli.md \
	uim-wayland.md
