.TH uim-xim 1 "March 19, 2005" "" ""
.SH NAME
\fBuim\-xim \fP- XIM interface to uim
.SH SYNOPSIS
.nf
.fam C
uim\-xim [\fIoptions\fP] 
.fam T
.fi
.SH DESCRIPTION
uim\-xim is a XIM interface to UIM that allows programs that can only
interface with XIM input methods to work with UIM.
.SH OPTIONS

.TP
.B
\--help
Show usage
.TP
.B
\--version
Show version
.TP
.B
\--list
List available backend conversion engines
.TP
.B
\--engine=ENGINE
Use ENGINE as a backend conversion engine at startup
.TP
.B
\--async
Use on-demand-synchronous method of XIM event flow
(using this option is not safe for Tcl/Tk GUI toolkit)
.TP
.B
\--trace
Trace connections
.TP
.B
\--trace-xim
Trace XIM messages
.SH AUTHOR
This manual page was written by Wesley J. Landaker <wjl@icecavern.net>,
for the Debian project (but may be used by others). 
