# Built into libreplace in uim/meson.build, after config.h, which these
# need, is generated there.
replace_sources = files(
  'bsd-asprintf.c',
  'bsd-misc.c',
  'bsd-poll.c',
  'bsd-snprintf.c',
  'daemon.c',
  'fake-rfc2553.c',
  'getpeereid.c',
  'setenv.c',
  'strlcat.c',
  'strlcpy.c',
  'strsep.c',
  'strtoll.c',
  'strtonum.c',
)
replace_include_directories = include_directories('.')
