#! /usr/bin/env sscm -C UTF-8
;; -*- buffer-file-coding-system: utf-8 -*-

;;  Filename : test-equal.scm
;;  About    : unit tests for equal?
;;
;;  Copyright (C) 2006 YAMAMOTO Kengo <yamaken AT bp.iij4u.or.jp>
;;
;;  All rights reserved.
;;
;;  Redistribution and use in source and binary forms, with or without
;;  modification, are permitted provided that the following conditions
;;  are met:
;;
;;  1. Redistributions of source code must retain the above copyright
;;     notice, this list of conditions and the following disclaimer.
;;  2. Redistributions in binary form must reproduce the above copyright
;;     notice, this list of conditions and the following disclaimer in the
;;     documentation and/or other materials provided with the distribution.
;;  3. Neither the name of authors nor the names of its contributors
;;     may be used to endorse or promote products derived from this software
;;     without specific prior written permission.
;;
;;  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS ``AS
;;  IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
;;  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
;;  PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR
;;  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
;;  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
;;  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
;;  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
;;  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
;;  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
;;  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

(load "test/unittest.scm")

(define tn test-name)

(tn "equal? invalid form")
(assert-error  (tn) (lambda () (equal?)))
(assert-error  (tn) (lambda () (equal? #f)))
(assert-error  (tn) (lambda () (equal? #f #f #f)))

(tn "equal? different types")
(assert-false  (tn) (equal? 1 #\1))
(assert-false  (tn) (equal? #\1 "1"))
(assert-false  (tn) (equal? #\1 '("1")))
(assert-false  (tn) (equal? '#("1") '("1")))

(tn "equal? boolean")
(assert-true   (tn) (equal? #f #f))
(assert-false  (tn) (equal? #f #t))
(assert-false  (tn) (equal? #t #f))
(assert-true   (tn) (equal? #t #t))

(tn "equal? null")
(assert-true   (tn) (equal? '() '()))
(if (and (provided? "sigscheme")
         (provided? "siod-bugs"))
    (begin
      (assert-true   (tn) (equal? #f '()))
      (assert-true   (tn) (equal? '() #f)))
    (begin
      (assert-false  (tn) (equal? #f '()))
      (assert-false  (tn) (equal? '() #f))))
(if (symbol-bound? 'vector?)
    (begin
      (assert-false  (tn) (equal? '() '#()))
      (assert-false  (tn) (equal? '#() '()))))

(tn "equal? #<eof>")
(if (provided? "sigscheme")
    (begin
      (assert-true   (tn) (equal? (eof) (eof)))
      (assert-false  (tn) (equal? (eof) (undef)))
      (assert-false  (tn) (equal? (undef) (eof)))
      (assert-false  (tn) (equal? '() (eof)))
      (assert-false  (tn) (equal? (eof) '()))
      (assert-false  (tn) (equal? #f (eof)))
      (assert-false  (tn) (equal? (eof) #f))))

(tn "equal? #<undef>")
(if (provided? "sigscheme")
    (begin
      (assert-true   (tn) (equal? (undef) (undef)))
      (assert-false  (tn) (equal? (eof) (undef)))
      (assert-false  (tn) (equal? (undef) (eof)))
      (assert-false  (tn) (equal? '() (undef)))
      (assert-false  (tn) (equal? (undef) '()))
      (assert-false  (tn) (equal? #f (undef)))
      (assert-false  (tn) (equal? (undef) #f))))

(tn "equal? integer")
(assert-true   (tn) (equal? 0 0))
(assert-true   (tn) (equal? 1 1))
(assert-true   (tn) (equal? 3 3))
(assert-true   (tn) (equal? -1 -1))
(assert-true   (tn) (equal? -3 -3))

(assert-false  (tn) (equal? 0 1))
(assert-false  (tn) (equal? 1 0))
(assert-false  (tn) (equal? 1 3))
(assert-false  (tn) (equal? 3 1))
(assert-false  (tn) (equal? -1 1))
(assert-false  (tn) (equal? 1 -1))
(assert-false  (tn) (equal? -3 3))
(assert-false  (tn) (equal? 3 -3))
(assert-false  (tn) (equal? -1 -3))
(assert-false  (tn) (equal? -3 -1))

(tn "equal? symbol")
(assert-true   (tn) (equal? 'symbol 'symbol))
(assert-false  (tn) (equal? 'symbol1 'symbol2))
(if (and (provided? "sigscheme")
         (provided? "strict-r5rs"))
    (begin
      (assert-true   (tn) (equal? 'symbol 'SYMBOL))
      (assert-true   (tn) (equal? 'SYMBOL 'symbol))
      (assert-true   (tn) (equal? 'symbol 'Symbol))
      (assert-true   (tn) (equal? 'Symbol 'symbol))
      (assert-true   (tn) (equal? 'symbol 'syMBoL))
      (assert-true   (tn) (equal? 'syMBoL 'symbol)))
    (begin
      (assert-false  (tn) (equal? 'symbol 'SYMBOL))
      (assert-false  (tn) (equal? 'SYMBOL 'symbol))
      (assert-false  (tn) (equal? 'symbol 'Symbol))
      (assert-false  (tn) (equal? 'Symbol 'symbol))
      (assert-false  (tn) (equal? 'symbol 'syMBoL))
      (assert-false  (tn) (equal? 'syMBoL 'symbol))))

(tn "equal? singlebyte char")
(assert-true   (tn) (equal? #\a #\a))
(assert-false  (tn) (equal? #\a #\b))
(assert-false  (tn) (equal? #\b #\a))
(assert-true   (tn) (equal? #\b #\b))

(let ((c1 #\a)
      (c2 #\b))
  (assert-true   (tn) (equal? c1 c1))
  (assert-true   (tn) (equal? c2 c2)))

(tn "equal? multibyte char")
(assert-true   (tn) (equal? #\あ #\あ))
(assert-false  (tn) (equal? #\あ #\い))
(assert-false  (tn) (equal? #\い #\あ))
(assert-true   (tn) (equal? #\い #\い))

(let ((c1 #\あ)
      (c2 #\い))
  (assert-true   (tn) (equal? c1 c1))
  (assert-true   (tn) (equal? c2 c2)))

(tn "equal? singlebyte string")
(assert-true   (tn) (equal? "" ""))
(assert-true   (tn) (equal? "a" "a"))
(assert-true   (tn) (equal? "b" "b"))
(assert-true   (tn) (equal? "aBc12!" "aBc12!"))
(let ((s1 "")
      (s2 "a")
      (s3 "b")
      (s4 "aBc12!"))
  (assert-true   (tn) (equal? s1 s1))
  (assert-true   (tn) (equal? s2 s2))
  (assert-true   (tn) (equal? s3 s3))
  (assert-true   (tn) (equal? s4 s4)))
(assert-false  (tn) (equal? "" "a"))
(assert-false  (tn) (equal? "a" ""))
(assert-false  (tn) (equal? "a" "b"))
(assert-false  (tn) (equal? "b" "a"))
(assert-false  (tn) (equal? "a" "A"))
(assert-false  (tn) (equal? "A" "a"))
(assert-false  (tn) (equal? "aBc123!" "aBc12!"))
(assert-false  (tn) (equal? "aBc12!" "aBc123!"))

(tn "equal? multibyte string")
(assert-true   (tn) (equal? "あ" "あ"))
(assert-true   (tn) (equal? "い" "い"))
(assert-true   (tn) (equal? "あ0イう12!" "あ0イう12!"))
(let ((s1 "あ")
      (s2 "い")
      (s3 "あ0イう12!"))
  (assert-true   (tn) (equal? s1 s1))
  (assert-true   (tn) (equal? s2 s2))
  (assert-true   (tn) (equal? s3 s3)))
(assert-false  (tn) (equal? "" "あ"))
(assert-false  (tn) (equal? "あ" ""))
(assert-false  (tn) (equal? "あ" "い"))
(assert-false  (tn) (equal? "い" "あ"))
(assert-false  (tn) (equal? "あ" "ア"))
(assert-false  (tn) (equal? "ア" "あ"))
(assert-false  (tn) (equal? "あ0イうぇ12!" "あ0イう12!"))
(assert-false  (tn) (equal? "あ0イう12!" "あ0イうぇ12!"))

(tn "equal? procedure")
(assert-true   (tn) (equal? + +))
(assert-false  (tn) (equal? + -))
(assert-false  (tn) (equal? - +))
(assert-true   (tn) (equal? - -))
(let ((plus +))
  (assert-true   (tn) (equal? + plus))
  (assert-true   (tn) (equal? plus +))
  (assert-true   (tn) (equal? plus plus)))

(tn "equal? syntax")
(assert-true   (tn) (equal? if if))
(assert-false  (tn) (equal? if set!))
(assert-false  (tn) (equal? set! if))
(assert-true   (tn) (equal? set! set!))
;; (define syntax if) is an invalid form

;; FIXME
(tn "equal? macro")
(if (symbol-bound? 'let-syntax)
    (let-syntax ((macro1 (syntax-rules ()
                           ((_) 'macro1-expanded)))
                 (macro2 (syntax-rules ()
                           ((_) 'macro2-expanded))))
      (assert-true   (tn) (equal? macro1 macro1))
      (assert-false  (tn) (equal? macro2 macro1))
      (assert-false  (tn) (equal? macro1 macro2))
      (assert-true   (tn) (equal? macro2 macro2))))

(tn "equal? closure")
(let ((closure (lambda () #t)))
  (assert-true   (tn) (equal? closure closure))
  (if (provided? "sigscheme")
      (begin
        (assert-false  (tn) (equal? closure (lambda () #t)))
        (assert-false  (tn) (equal? (lambda () #t) closure))
        (assert-false  (tn) (equal? (lambda () #t) (lambda () #t))))))

(tn "equal? stateful closure")
(let ((stateful (lambda ()
                  (let ((state 0))
                    (lambda ()
                      (set! state (+ state 1))
                      state)))))
  (assert-true   (tn) (equal? stateful stateful))
  (assert-false  (tn) (equal? (stateful) (stateful))))

(let ((may-be-optimized-out (lambda ()
                              (let ((state 0))
                                (lambda ()
                                  (set! state (+ state 1))
                                  0)))))
  (assert-true   (tn) (equal? may-be-optimized-out may-be-optimized-out))
  (if (provided? "sigscheme")
      (assert-false (tn) (equal? (may-be-optimized-out) (may-be-optimized-out)))))

(letrec ((may-be-unified1 (lambda ()
                            (if (equal? may-be-unified1
                                        may-be-unified2)
                                'optimized-out
                                'not-unified1)))
         (may-be-unified2 (lambda ()
                            (if (equal? may-be-unified1
                                        may-be-unified2)
                                'optimized-out
                                'not-unified2))))
  (if (provided? "sigscheme")
      (begin
        (assert-false  (tn) (equal? may-be-unified1 may-be-unified2))
        (assert-false  (tn) (equal? (may-be-unified1) (may-be-unified2))))
      (begin
        ;; other implementations may pass this
        ;;(assert-true   (tn) (equal? may-be-unified1 may-be-unified2))
        ;;(assert-true   (tn) (equal? (may-be-unified1) (may-be-unified2)))
        )))

(tn "equal? continuation")
(call-with-current-continuation
 (lambda (k1)
   (call-with-current-continuation
    (lambda (k2)
      (assert-true   (tn) (equal? k1 k1))
      (assert-false  (tn) (equal? k1 k2))
      (assert-false  (tn) (equal? k2 k1))
      (assert-true   (tn) (equal? k2 k2))
      (let ((cont k1))
        (assert-true   (tn) (equal? cont cont))
        (assert-true   (tn) (equal? cont k1))
        (assert-true   (tn) (equal? k1 cont))
        (assert-false  (tn) (equal? cont k2))
        (assert-false  (tn) (equal? k2 cont)))))))

(tn "equal? port")
(assert-true   (tn) (equal? (current-output-port) (current-output-port)))
(assert-false  (tn) (equal? (current-input-port) (current-output-port)))
(assert-false  (tn) (equal? (current-output-port) (current-input-port)))
(assert-true   (tn) (equal? (current-input-port) (current-input-port)))
(let ((port (current-input-port)))
  (assert-true   (tn) (equal? port port))
  (assert-true   (tn) (equal? (current-input-port) port))
  (assert-true   (tn) (equal? port (current-input-port)))
  (assert-false  (tn) (equal? (current-output-port) port))
  (assert-false  (tn) (equal? port (current-output-port))))

(tn "equal? pair")
(assert-true   (tn) (equal? '(#t . #t) '(#t . #t)))
(assert-true   (tn) (equal? '(#f . #t) '(#f . #t)))
(assert-true   (tn) (equal? '(#t . #f) '(#t . #f)))
(assert-false  (tn) (equal? '(#f . #t) '(#t . #f)))
(assert-true   (tn) (equal? '(#\a . #\a) '(#\a . #\a)))
(assert-true   (tn) (equal? '(#\a . #\b) '(#\a . #\b)))
(assert-true   (tn) (equal? '(#\b . #\a) '(#\b . #\a)))
(assert-false  (tn) (equal? '(#\a . #\b) '(#\b . #\a)))
(assert-true   (tn) (equal? '("a" . "a") '("a" . "a")))
(assert-true   (tn) (equal? '("a" . "b") '("a" . "b")))
(assert-true   (tn) (equal? '("b" . "a") '("b" . "a")))
(assert-false  (tn) (equal? '("a" . "b") '("b" . "a")))

(assert-true   (tn) (equal? (cons #t #t) (cons #t #t)))
(assert-true   (tn) (equal? (cons #f #t) (cons #f #t)))
(assert-true   (tn) (equal? (cons #t #f) (cons #t #f)))
(assert-false  (tn) (equal? (cons #f #t) (cons #t #f)))
(assert-true   (tn) (equal? (cons #\a #\a) (cons #\a #\a)))
(assert-true   (tn) (equal? (cons #\a #\b) (cons #\a #\b)))
(assert-true   (tn) (equal? (cons #\b #\a) (cons #\b #\a)))
(assert-false  (tn) (equal? (cons #\a #\b) (cons #\b #\a)))
(assert-true   (tn) (equal? (cons "a" "a") (cons "a" "a")))
(assert-true   (tn) (equal? (cons "a" "b") (cons "a" "b")))
(assert-true   (tn) (equal? (cons "b" "a") (cons "b" "a")))
(assert-false  (tn) (equal? (cons "a" "b") (cons "b" "a")))

(tn "equal? list")
(assert-true   (tn) (equal? '(#f) '(#f)))
(assert-false  (tn) (equal? '(#f) '(#t)))
(assert-false  (tn) (equal? '(#t) '(#f)))
(assert-true   (tn) (equal? '(#t) '(#t)))
(assert-true   (tn) (equal? '((#f)) '((#f))))
(assert-false  (tn) (equal? '((#f)) '((#t))))
(assert-false  (tn) (equal? '((#t)) '((#f))))
(assert-true   (tn) (equal? '((#t)) '((#t))))
(assert-true   (tn) (equal? '(1) '(1)))
(assert-false  (tn) (equal? '(1) '(0)))
(assert-true   (tn) (equal? '(1 3 5 0 13)
                            '(1 3 5 0 13)))
(assert-false  (tn) (equal? '(1 3 2 0 13)
                            '(1 3 5 0 13)))
(assert-true   (tn) (equal? '(1 3 (5 0 13))
                            '(1 3 (5 0 13))))
(assert-false  (tn) (equal? '(1 3 (2 0 13))
                            '(1 3 (5 0 13))))
(assert-true   (tn) (equal? '((1)) '((1))))
(assert-false  (tn) (equal? '((1)) '((0))))
(assert-true   (tn) (equal? '((1) (3) (5) (0) (13))
                            '((1) (3) (5) (0) (13))))
(assert-false  (tn) (equal? '((1) (3) (2) (0) (13))
                            '((1) (3) (5) (0) (13))))
(assert-true   (tn) (equal? '(#\a) '(#\a)))
(assert-false  (tn) (equal? '(#\a) '(#\b)))
(assert-false  (tn) (equal? '(#\b) '(#\a)))
(assert-true   (tn) (equal? '((#\a)) '((#\a))))
(assert-false  (tn) (equal? '((#\a)) '((#\b))))
(assert-false  (tn) (equal? '((#\b)) '((#\a))))

(assert-true   (tn) (equal? (list #f) (list #f)))
(assert-false  (tn) (equal? (list #f) (list #t)))
(assert-false  (tn) (equal? (list #t) (list #f)))
(assert-true   (tn) (equal? (list #t) (list #t)))
(assert-true   (tn) (equal? (list (list #f)) (list (list #f))))
(assert-false  (tn) (equal? (list (list #f)) (list (list #t))))
(assert-false  (tn) (equal? (list (list #t)) (list (list #f))))
(assert-true   (tn) (equal? (list (list #t)) (list (list #t))))
(assert-true   (tn) (equal? (list 1) (list 1)))
(assert-false  (tn) (equal? (list 1) (list 0)))
(assert-true   (tn) (equal? (list 1 3 5 0 13)
                            (list 1 3 5 0 13)))
(assert-false  (tn) (equal? (list 1 3 2 0 13)
                            (list 1 3 5 0 13)))
(assert-true   (tn) (equal? (list 1 3 (list 5 0 13))
                            (list 1 3 (list 5 0 13))))
(assert-false  (tn) (equal? (list 1 3 (list 2 0 13))
                            (list 1 3 (list 5 0 13))))
(assert-true   (tn) (equal? (list (list 1)) (list (list 1))))
(assert-false  (tn) (equal? (list (list 1)) (list (list 0))))
(assert-true   (tn) (equal? (list (list 1) (list 3) (list 5) (list 0) (list 13))
                            (list (list 1) (list 3) (list 5) (list 0) (list 13))))
(assert-false  (tn) (equal? (list (list 1) (list 3) (list 2) (list 0) (list 13))
                            (list (list 1) (list 3) (list 5) (list 0) (list 13))))
(assert-true   (tn) (equal? (list #\a) (list #\a)))
(assert-false  (tn) (equal? (list #\a) (list #\b)))
(assert-false  (tn) (equal? (list #\b) (list #\a)))
(assert-true   (tn) (equal? (list (list #\a)) (list (list #\a))))
(assert-false  (tn) (equal? (list (list #\a)) (list (list #\b))))
(assert-false  (tn) (equal? (list (list #\b)) (list (list #\a))))

(assert-true   (tn) (equal? '("") '("")))
(assert-true   (tn) (equal? '(("")) '((""))))
(assert-true   (tn) (equal? '("aBc12!")
                            '("aBc12!")))
(assert-true   (tn) (equal? '("あ0イう12!")
                            '("あ0イう12!")))
(assert-true   (tn) (equal? '("a" "" "aB1" ("3c" "d") "a")
                            '("a" "" "aB1" ("3c" "d") "a")))
(assert-true   (tn) (equal? '(("aBc12!"))
                            '(("aBc12!"))))
(assert-true   (tn) (equal? '(("あ0イう12!"))
                            '(("あ0イう12!"))))

(assert-true   (tn) (equal? (list "") (list "")))
(assert-true   (tn) (equal? (list (list "")) (list (list ""))))
(assert-true   (tn) (equal? (list "aBc12!")
                            (list "aBc12!")))
(assert-true   (tn) (equal? (list "あ0イう12!")
                            (list "あ0イう12!")))
(assert-true   (tn) (equal? (list "a" "" "aB1" (list "3c" "d") "a")
                            (list "a" "" "aB1" (list "3c" "d") "a")))
(assert-true   (tn) (equal? (list (list "aBc12!"))
                            (list (list "aBc12!"))))
(assert-true   (tn) (equal? (list (list "あ0イう12!"))
                            (list (list "あ0イう12!"))))

(assert-false  (tn) (equal? '("aBc123!")
                            '("aBc12!")))
(assert-false  (tn) (equal? '("あ0イぅ12!")
                            '("あ0イう12!")))
(assert-false  (tn) (equal? '("a" "" "aB1" ("3c" "e") "a")
                            '("a" "" "aB1" ("3c" "d") "a")))
(assert-false  (tn) (equal? '(("aBc123!"))
                            '(("aBc12!"))))
(assert-false  (tn) (equal? '(("あ0イぅ12!"))
                            '(("あ0イう12!"))))

(assert-false  (tn) (equal? (list "aBc123!")
                            (list "aBc12!")))
(assert-false  (tn) (equal? (list "あ0イぅ12!")
                            (list "あ0イう12!")))
(assert-false  (tn) (equal? (list "a" "" "aB1" (list "3c" "e") "a")
                            (list "a" "" "aB1" (list "3c" "d") "a")))
(assert-false  (tn) (equal? (list (list "aBc123!"))
                            (list (list "aBc12!"))))
(assert-false  (tn) (equal? (list (list "あ0イぅ12!"))
                            (list (list "あ0イう12!"))))

(assert-true   (tn)
               (equal? '(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)
                       '(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)))
(assert-false  (tn)
               (equal? '(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)
                       '(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("L")) #t)))
(assert-false  (tn)
               (equal? '(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)
                       '(0 #\a "" ("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)))
(assert-false  (tn)
               (equal? '(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)
                       '(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" #t)))
(assert-false  (tn)
               (equal? '(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" #t)
                       '(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)))

(assert-true   (tn)
               (equal? (list 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (list -1 #\b '("Ls")) #t)
                       (list 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (list -1 #\b '("Ls")) #t)))
(assert-false  (tn)
               (equal? (list 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (list -1 #\b '("Ls")) #t)
                       (list 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (list -1 #\b '("L")) #t)))
(assert-false  (tn)
               (equal? (list 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (list -1 #\b '("Ls")) #t)
                       (list 0 #\a "" (list "vE" -1 '(#\?))   23 + "aBc" (list -1 #\b '("Ls")) #t)))
(assert-false  (tn)
               (equal? (list 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (list -1 #\b '("Ls")) #t)
                       (list 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" #t)))
(assert-false  (tn)
               (equal? (list 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" #t)
                       (list 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (list -1 #\b '("Ls")) #t)))

(tn "equal? empty vector")
(assert-true   (tn) (equal? '#() '#()))
(assert-true   (tn) (equal? (vector) (vector)))

(let ((v1 '#())
      (v2 (vector)))
  (assert-true   (tn) (equal? v1 v1))
  (assert-true   (tn) (equal? v2 v2))
  (assert-true   (tn) (equal? v1 v2)))

(tn "equal? vector")
(assert-true   (tn) (equal? '#(#f) '#(#f)))
(assert-false  (tn) (equal? '#(#f) '#(#t)))
(assert-false  (tn) (equal? '#(#t) '#(#f)))
(assert-true   (tn) (equal? '#(#t) '#(#t)))
(assert-true   (tn) (equal? '#(#(#f)) '#(#(#f))))
(assert-false  (tn) (equal? '#(#(#f)) '#(#(#t))))
(assert-false  (tn) (equal? '#(#(#t)) '#(#(#f))))
(assert-true   (tn) (equal? '#(#(#t)) '#(#(#t))))
(assert-true   (tn) (equal? '#(1) '#(1)))
(assert-false  (tn) (equal? '#(1) '#(0)))
(assert-true   (tn) (equal? '#(1 3 5 0 13)
                            '#(1 3 5 0 13)))
(assert-false  (tn) (equal? '#(1 3 2 0 13)
                            '#(1 3 5 0 13)))
(assert-true   (tn) (equal? '#(1 3 #(5 0 13))
                            '#(1 3 #(5 0 13))))
(assert-false  (tn) (equal? '#(1 3 #(2 0 13))
                            '#(1 3 #(5 0 13))))
(assert-true   (tn) (equal? '#(#(1)) '#(#(1))))
(assert-false  (tn) (equal? '#(#(1)) '#(#(0))))
(assert-true   (tn) (equal? '#(#(1) #(3) #(5) #(0) #(13))
                            '#(#(1) #(3) #(5) #(0) #(13))))
(assert-false  (tn) (equal? '#(#(1) #(3) #(2) #(0) #(13))
                            '#(#(1) #(3) #(5) #(0) #(13))))
(assert-true   (tn) (equal? '#(#\a) '#(#\a)))
(assert-false  (tn) (equal? '#(#\a) '#(#\b)))
(assert-false  (tn) (equal? '#(#\b) '#(#\a)))
(assert-true   (tn) (equal? '#(#(#\a)) '#(#(#\a))))
(assert-false  (tn) (equal? '#(#(#\a)) '#(#(#\b))))
(assert-false  (tn) (equal? '#(#(#\b)) '#(#(#\a))))

(assert-true   (tn) (equal? (vector #f) (vector #f)))
(assert-false  (tn) (equal? (vector #f) (vector #t)))
(assert-false  (tn) (equal? (vector #t) (vector #f)))
(assert-true   (tn) (equal? (vector #t) (vector #t)))
(assert-true   (tn) (equal? (vector (vector #f)) (vector (vector #f))))
(assert-false  (tn) (equal? (vector (vector #f)) (vector (vector #t))))
(assert-false  (tn) (equal? (vector (vector #t)) (vector (vector #f))))
(assert-true   (tn) (equal? (vector (vector #t)) (vector (vector #t))))
(assert-true   (tn) (equal? (vector 1) (vector 1)))
(assert-false  (tn) (equal? (vector 1) (vector 0)))
(assert-true   (tn) (equal? (vector 1 3 5 0 13)
                            (vector 1 3 5 0 13)))
(assert-false  (tn) (equal? (vector 1 3 2 0 13)
                            (vector 1 3 5 0 13)))
(assert-true   (tn) (equal? (vector 1 3 (vector 5 0 13))
                            (vector 1 3 (vector 5 0 13))))
(assert-false  (tn) (equal? (vector 1 3 (vector 2 0 13))
                            (vector 1 3 (vector 5 0 13))))
(assert-true   (tn) (equal? (vector (vector 1)) (vector (vector 1))))
(assert-false  (tn) (equal? (vector (vector 1)) (vector (vector 0))))
(assert-true   (tn) (equal? (vector (vector 1) (vector 3) (vector 5) (vector 0) (vector 13))
                            (vector (vector 1) (vector 3) (vector 5) (vector 0) (vector 13))))
(assert-false  (tn) (equal? (vector (vector 1) (vector 3) (vector 2) (vector 0) (vector 13))
                            (vector (vector 1) (vector 3) (vector 5) (vector 0) (vector 13))))
(assert-true   (tn) (equal? (vector #\a) (vector #\a)))
(assert-false  (tn) (equal? (vector #\a) (vector #\b)))
(assert-false  (tn) (equal? (vector #\b) (vector #\a)))
(assert-true   (tn) (equal? (vector (vector #\a)) (vector (vector #\a))))
(assert-false  (tn) (equal? (vector (vector #\a)) (vector (vector #\b))))
(assert-false  (tn) (equal? (vector (vector #\b)) (vector (vector #\a))))

(assert-true   (tn) (equal? '#("") '#("")))
(assert-true   (tn) (equal? '#(#("")) '#(#(""))))
(assert-true   (tn) (equal? '#("aBc12!")
                            '#("aBc12!")))
(assert-true   (tn) (equal? '#("あ0イう12!")
                            '#("あ0イう12!")))
(assert-true   (tn) (equal? '#("a" "" "aB1" #("3c" "d") "a")
                            '#("a" "" "aB1" #("3c" "d") "a")))
(assert-true   (tn) (equal? '#(#("aBc12!"))
                            '#(#("aBc12!"))))
(assert-true   (tn) (equal? '#(#("あ0イう12!"))
                            '#(#("あ0イう12!"))))

(assert-true   (tn) (equal? (vector "") (vector "")))
(assert-true   (tn) (equal? (vector (vector "")) (vector (vector ""))))
(assert-true   (tn) (equal? (vector "aBc12!")
                            (vector "aBc12!")))
(assert-true   (tn) (equal? (vector "あ0イう12!")
                            (vector "あ0イう12!")))
(assert-true   (tn) (equal? (vector "a" "" "aB1" (vector "3c" "d") "a")
                            (vector "a" "" "aB1" (vector "3c" "d") "a")))
(assert-true   (tn) (equal? (vector (vector "aBc12!"))
                            (vector (vector "aBc12!"))))
(assert-true   (tn) (equal? (vector (vector "あ0イう12!"))
                            (vector (vector "あ0イう12!"))))

(assert-false  (tn) (equal? '#("aBc123!")
                            '#("aBc12!")))
(assert-false  (tn) (equal? '#("あ0イぅ12!")
                            '#("あ0イう12!")))
(assert-false  (tn) (equal? '#("a" "" "aB1" #("3c" "e") "a")
                            '#("a" "" "aB1" #("3c" "d") "a")))
(assert-false  (tn) (equal? '#(#("aBc123!"))
                            '#(#("aBc12!"))))
(assert-false  (tn) (equal? '#(#("あ0イぅ12!"))
                            '#(#("あ0イう12!"))))

(assert-false  (tn) (equal? (vector "aBc123!")
                            (vector "aBc12!")))
(assert-false  (tn) (equal? (vector "あ0イぅ12!")
                            (vector "あ0イう12!")))
(assert-false  (tn) (equal? (vector "a" "" "aB1" (vector "3c" "e") "a")
                            (vector "a" "" "aB1" (vector "3c" "d") "a")))
(assert-false  (tn) (equal? (vector (vector "aBc123!"))
                            (vector (vector "aBc12!"))))
(assert-false  (tn) (equal? (vector (vector "あ0イぅ12!"))
                            (vector (vector "あ0イう12!"))))

(assert-true   (tn)
               (equal? '#(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)
                       '#(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)))
(assert-false  (tn)
               (equal? '#(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)
                       '#(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("L")) #t)))
(assert-false  (tn)
               (equal? '#(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)
                       '#(0 #\a "" ("vE" -1 (#\?))  23 + "aBc" (-1 #\b ("Ls")) #t)))
(assert-false  (tn)
               (equal? '#(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)
                       '#(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" #t)))
(assert-false  (tn)
               (equal? '#(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" #t)
                       '#(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)))

(assert-true   (tn)
               (equal? (vector 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (vector -1 #\b '("Ls")) #t)
                       (vector 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (vector -1 #\b '("Ls")) #t)))
(assert-false  (tn)
               (equal? (vector 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (vector -1 #\b '("Ls")) #t)
                       (vector 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (vector -1 #\b '("L")) #t)))
(assert-false  (tn)
               (equal? (vector 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (vector -1 #\b '("Ls")) #t)
                       (vector 0 #\a "" (list "vE" -1 '(#\?))   23 + "aBc" (vector -1 #\b '("Ls")) #t)))
(assert-false  (tn)
               (equal? (vector 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (vector -1 #\b '("Ls")) #t)
                       (vector 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" #t)))
(assert-false  (tn)
               (equal? (vector 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" #t)
                       (vector 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (vector -1 #\b '("Ls")) #t)))


(total-report)
