#! /usr/bin/env sscm -C UTF-8
;; -*- buffer-file-coding-system: utf-8 -*-

;;  Filename : test-eq.scm
;;  About    : unit tests for eq?
;;
;;  Copyright (C) 2006 YAMAMOTO Kengo <yamaken AT bp.iij4u.or.jp>
;;
;;  All rights reserved.
;;
;;  Redistribution and use in source and binary forms, with or without
;;  modification, are permitted provided that the following conditions
;;  are met:
;;
;;  1. Redistributions of source code must retain the above copyright
;;     notice, this list of conditions and the following disclaimer.
;;  2. Redistributions in binary form must reproduce the above copyright
;;     notice, this list of conditions and the following disclaimer in the
;;     documentation and/or other materials provided with the distribution.
;;  3. Neither the name of authors nor the names of its contributors
;;     may be used to endorse or promote products derived from this software
;;     without specific prior written permission.
;;
;;  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS ``AS
;;  IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
;;  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
;;  PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR
;;  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
;;  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
;;  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
;;  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
;;  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
;;  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
;;  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

(load "test/unittest.scm")

(define tn test-name)

(tn "eq? invalid form")
(assert-error  (tn) (lambda () (eq?)))
(assert-error  (tn) (lambda () (eq? #f)))
(assert-error  (tn) (lambda () (eq? #f #f #f)))

(tn "eq? different types")
(assert-false  (tn) (eq? 1 #\1))
(assert-false  (tn) (eq? #\1 "1"))
(assert-false  (tn) (eq? #\1 '("1")))
(assert-false  (tn) (eq? '#("1") '("1")))

(tn "eq? boolean")
(assert-true   (tn) (eq? #f #f))
(assert-false  (tn) (eq? #f #t))
(assert-false  (tn) (eq? #t #f))
(assert-true   (tn) (eq? #t #t))

(tn "eq? null")
(assert-true   (tn) (eq? '() '()))
(if (and (provided? "sigscheme")
         (provided? "siod-bugs"))
    (begin
      (assert-true   (tn) (eq? #f '()))
      (assert-true   (tn) (eq? '() #f)))
    (begin
      (assert-false  (tn) (eq? #f '()))
      (assert-false  (tn) (eq? '() #f))))
(if (symbol-bound? 'vector?)
    (begin
      (assert-false  (tn) (eq? '() '#()))
      (assert-false  (tn) (eq? '#() '()))))

(tn "eq? #<eof>")
(if (provided? "sigscheme")
    (begin
      (assert-true   (tn) (eq? (eof) (eof)))
      (assert-false  (tn) (eq? (eof) (undef)))
      (assert-false  (tn) (eq? (undef) (eof)))
      (assert-false  (tn) (eq? '() (eof)))
      (assert-false  (tn) (eq? (eof) '()))
      (assert-false  (tn) (eq? #f (eof)))
      (assert-false  (tn) (eq? (eof) #f))))

(tn "eq? #<undef>")
(if (provided? "sigscheme")
    (begin
      (assert-true   (tn) (eq? (undef) (undef)))
      (assert-false  (tn) (eq? (eof) (undef)))
      (assert-false  (tn) (eq? (undef) (eof)))
      (assert-false  (tn) (eq? '() (undef)))
      (assert-false  (tn) (eq? (undef) '()))
      (assert-false  (tn) (eq? #f (undef)))
      (assert-false  (tn) (eq? (undef) #f))))

(tn "eq? integer")
(if (and (provided? "sigscheme")
         (provided? "immediate-number-only"))
    (begin
      (assert-true   (tn) (eq? 0 0))
      (assert-true   (tn) (eq? 1 1))
      (assert-true   (tn) (eq? 3 3))
      (assert-true   (tn) (eq? -1 -1))
      (assert-true   (tn) (eq? -3 -3))

      (assert-false  (tn) (eq? 0 1))
      (assert-false  (tn) (eq? 1 0))
      (assert-false  (tn) (eq? 1 3))
      (assert-false  (tn) (eq? 3 1))
      (assert-false  (tn) (eq? -1 1))
      (assert-false  (tn) (eq? 1 -1))
      (assert-false  (tn) (eq? -3 3))
      (assert-false  (tn) (eq? 3 -3))
      (assert-false  (tn) (eq? -1 -3))
      (assert-false  (tn) (eq? -3 -1))))

(tn "eq? symbol")
(assert-true   (tn) (eq? 'symbol 'symbol))
(assert-false  (tn) (eq? 'symbol1 'symbol2))
(if (and (provided? "sigscheme")
         (provided? "strict-r5rs"))
    (begin
      (assert-true   (tn) (eq? 'symbol 'SYMBOL))
      (assert-true   (tn) (eq? 'SYMBOL 'symbol))
      (assert-true   (tn) (eq? 'symbol 'Symbol))
      (assert-true   (tn) (eq? 'Symbol 'symbol))
      (assert-true   (tn) (eq? 'symbol 'syMBoL))
      (assert-true   (tn) (eq? 'syMBoL 'symbol)))
    (begin
      (assert-false  (tn) (eq? 'symbol 'SYMBOL))
      (assert-false  (tn) (eq? 'SYMBOL 'symbol))
      (assert-false  (tn) (eq? 'symbol 'Symbol))
      (assert-false  (tn) (eq? 'Symbol 'symbol))
      (assert-false  (tn) (eq? 'symbol 'syMBoL))
      (assert-false  (tn) (eq? 'syMBoL 'symbol))))

(tn "eq? singlebyte char")
(if (provided? "sigscheme")
    (if (provided? "immediate-char-only")
        (begin
          (assert-true   (tn) (eq? #\a #\a))
          (assert-false  (tn) (eq? #\a #\b))
          (assert-false  (tn) (eq? #\b #\a))
          (assert-true   (tn) (eq? #\b #\b)))
        (begin
          (assert-false  (tn) (eq? #\a #\a))
          (assert-false  (tn) (eq? #\a #\b))
          (assert-false  (tn) (eq? #\b #\a))
          (assert-false  (tn) (eq? #\b #\b)))))

(let ((c1 #\a)
      (c2 #\b))
  (assert-true   (tn) (eq? c1 c1))
  (assert-true   (tn) (eq? c2 c2)))

(tn "eq? multibyte char")
(if (provided? "sigscheme")
    (if (provided? "immediate-char-only")
        (begin
          (assert-true   (tn) (eq? #\あ #\あ))
          (assert-false  (tn) (eq? #\あ #\い))
          (assert-false  (tn) (eq? #\い #\あ))
          (assert-true   (tn) (eq? #\い #\い)))
        (begin
          (assert-false  (tn) (eq? #\あ #\あ))
          (assert-false  (tn) (eq? #\あ #\い))
          (assert-false  (tn) (eq? #\い #\あ))
          (assert-false  (tn) (eq? #\い #\い)))))

(let ((c1 #\あ)
      (c2 #\い))
  (assert-true   (tn) (eq? c1 c1))
  (assert-true   (tn) (eq? c2 c2)))

(tn "eq? singlebyte string")
(if (provided? "sigscheme")
    (begin
      (assert-false  (tn) (eq? "" ""))
      (assert-false  (tn) (eq? "a" "a"))
      (assert-false  (tn) (eq? "b" "b"))
      (assert-false  (tn) (eq? "aBc12!" "aBc12!"))))
(let ((s1 "")
      (s2 "a")
      (s3 "b")
      (s4 "aBc12!"))
  (assert-true   (tn) (eq? s1 s1))
  (assert-true   (tn) (eq? s2 s2))
  (assert-true   (tn) (eq? s3 s3))
  (assert-true   (tn) (eq? s4 s4)))
(assert-false  (tn) (eq? "" "a"))
(assert-false  (tn) (eq? "a" ""))
(assert-false  (tn) (eq? "a" "b"))
(assert-false  (tn) (eq? "b" "a"))
(assert-false  (tn) (eq? "a" "A"))
(assert-false  (tn) (eq? "A" "a"))
(assert-false  (tn) (eq? "aBc123!" "aBc12!"))
(assert-false  (tn) (eq? "aBc12!" "aBc123!"))

(tn "eq? multibyte string")
(if (provided? "sigscheme")
    (begin
      (assert-false  (tn) (eq? "あ" "あ"))
      (assert-false  (tn) (eq? "い" "い"))
      (assert-false  (tn) (eq? "あ0イう12!" "あ0イう12!"))))
(let ((s1 "あ")
      (s2 "い")
      (s3 "あ0イう12!"))
  (assert-true   (tn) (eq? s1 s1))
  (assert-true   (tn) (eq? s2 s2))
  (assert-true   (tn) (eq? s3 s3)))
(assert-false  (tn) (eq? "" "あ"))
(assert-false  (tn) (eq? "あ" ""))
(assert-false  (tn) (eq? "あ" "い"))
(assert-false  (tn) (eq? "い" "あ"))
(assert-false  (tn) (eq? "あ" "ア"))
(assert-false  (tn) (eq? "ア" "あ"))
(assert-false  (tn) (eq? "あ0イうぇ12!" "あ0イう12!"))
(assert-false  (tn) (eq? "あ0イう12!" "あ0イうぇ12!"))

(tn "eq? procedure")
(assert-true   (tn) (eq? + +))
(assert-false  (tn) (eq? + -))
(assert-false  (tn) (eq? - +))
(assert-true   (tn) (eq? - -))
(let ((plus +))
  (assert-true   (tn) (eq? + plus))
  (assert-true   (tn) (eq? plus +))
  (assert-true   (tn) (eq? plus plus)))

(tn "eq? syntax")
(assert-true   (tn) (eq? if if))
(assert-false  (tn) (eq? if set!))
(assert-false  (tn) (eq? set! if))
(assert-true   (tn) (eq? set! set!))
;; (define syntax if) is an invalid form

(tn "eq? macro")
(if (symbol-bound? 'let-syntax)
    (let-syntax ((macro1 (syntax-rules ()
                           ((_) 'macro1-expanded)))
                 (macro2 (syntax-rules ()
                           ((_) 'macro2-expanded))))
      (assert-true   (tn) (eq? macro1 macro1))
      (assert-false  (tn) (eq? macro2 macro1))
      (assert-false  (tn) (eq? macro1 macro2))
      (assert-true   (tn) (eq? macro2 macro2))))

(tn "eq? closure")
(let ((closure (lambda () #t)))
  (assert-true   (tn) (eq? closure closure))
  (if (provided? "sigscheme")
      (begin
        (assert-false  (tn) (eq? closure (lambda () #t)))
        (assert-false  (tn) (eq? (lambda () #t) closure))
        (assert-false  (tn) (eq? (lambda () #t) (lambda () #t))))))

(tn "eq? stateful closure")
(let ((stateful (lambda ()
                  (let ((state 0))
                    (lambda ()
                      (set! state (+ state 1))
                      state)))))
  (assert-true   (tn) (eq? stateful stateful))
  (assert-false  (tn) (eq? (stateful) (stateful))))

(let ((may-be-optimized-out (lambda ()
                              (let ((state 0))
                                (lambda ()
                                  (set! state (+ state 1))
                                  0)))))
  (assert-true   (tn) (eq? may-be-optimized-out may-be-optimized-out))
  (if (provided? "sigscheme")
      (assert-false (tn) (eq? (may-be-optimized-out) (may-be-optimized-out)))))

(letrec ((may-be-unified1 (lambda ()
                            (if (eq? may-be-unified1
                                     may-be-unified2)
                                'optimized-out
                                'not-unified1)))
         (may-be-unified2 (lambda ()
                            (if (eq? may-be-unified1
                                     may-be-unified2)
                                'optimized-out
                                'not-unified2))))
  (if (provided? "sigscheme")
      (begin
        (assert-false  (tn) (eq? may-be-unified1 may-be-unified2))
        (assert-false  (tn) (eq? (may-be-unified1) (may-be-unified2))))
      (begin
        ;; other implementations may pass this
        ;;(assert-true   (tn) (eq? may-be-unified1 may-be-unified2))
        ;;(assert-true   (tn) (eq? (may-be-unified1) (may-be-unified2)))
        )))

(tn "eq? continuation")
(call-with-current-continuation
 (lambda (k1)
   (call-with-current-continuation
    (lambda (k2)
      (assert-true   (tn) (eq? k1 k1))
      (assert-false  (tn) (eq? k1 k2))
      (assert-false  (tn) (eq? k2 k1))
      (assert-true   (tn) (eq? k2 k2))
      (let ((cont k1))
        (assert-true   (tn) (eq? cont cont))
        (assert-true   (tn) (eq? cont k1))
        (assert-true   (tn) (eq? k1 cont))
        (assert-false  (tn) (eq? cont k2))
        (assert-false  (tn) (eq? k2 cont)))))))

(tn "eq? port")
(assert-true   (tn) (eq? (current-output-port) (current-output-port)))
(assert-false  (tn) (eq? (current-input-port) (current-output-port)))
(assert-false  (tn) (eq? (current-output-port) (current-input-port)))
(assert-true   (tn) (eq? (current-input-port) (current-input-port)))
(let ((port (current-input-port)))
  (assert-true   (tn) (eq? port port))
  (assert-true   (tn) (eq? (current-input-port) port))
  (assert-true   (tn) (eq? port (current-input-port)))
  (assert-false  (tn) (eq? (current-output-port) port))
  (assert-false  (tn) (eq? port (current-output-port))))

(tn "eq? pair")
(if (provided? "sigscheme")
    (begin
      (assert-false  (tn) (eq? '(#t . #t) '(#t . #t)))
      (assert-false  (tn) (eq? '(#f . #t) '(#f . #t)))
      (assert-false  (tn) (eq? '(#t . #f) '(#t . #f)))
      (assert-false  (tn) (eq? '(#f . #t) '(#t . #f)))
      (assert-false  (tn) (eq? '(#\a . #\a) '(#\a . #\a)))
      (assert-false  (tn) (eq? '(#\a . #\b) '(#\a . #\b)))
      (assert-false  (tn) (eq? '(#\b . #\a) '(#\b . #\a)))
      (assert-false  (tn) (eq? '(#\a . #\b) '(#\b . #\a)))
      (assert-false  (tn) (eq? '("a" . "a") '("a" . "a")))
      (assert-false  (tn) (eq? '("a" . "b") '("a" . "b")))
      (assert-false  (tn) (eq? '("b" . "a") '("b" . "a")))
      (assert-false  (tn) (eq? '("a" . "b") '("b" . "a")))))

(assert-false  (tn) (eq? (cons #t #t) (cons #t #t)))
(assert-false  (tn) (eq? (cons #f #t) (cons #f #t)))
(assert-false  (tn) (eq? (cons #t #f) (cons #t #f)))
(assert-false  (tn) (eq? (cons #f #t) (cons #t #f)))
(assert-false  (tn) (eq? (cons #\a #\a) (cons #\a #\a)))
(assert-false  (tn) (eq? (cons #\a #\b) (cons #\a #\b)))
(assert-false  (tn) (eq? (cons #\b #\a) (cons #\b #\a)))
(assert-false  (tn) (eq? (cons #\a #\b) (cons #\b #\a)))
(assert-false  (tn) (eq? (cons "a" "a") (cons "a" "a")))
(assert-false  (tn) (eq? (cons "a" "b") (cons "a" "b")))
(assert-false  (tn) (eq? (cons "b" "a") (cons "b" "a")))
(assert-false  (tn) (eq? (cons "a" "b") (cons "b" "a")))

(tn "eq? list")
(if (provided? "sigscheme")
    (begin
      (assert-false  (tn) (eq? '(#f) '(#f)))
      (assert-false  (tn) (eq? '(#f) '(#t)))
      (assert-false  (tn) (eq? '(#t) '(#f)))
      (assert-false  (tn) (eq? '(#t) '(#t)))
      (assert-false  (tn) (eq? '((#f)) '((#f))))
      (assert-false  (tn) (eq? '((#f)) '((#t))))
      (assert-false  (tn) (eq? '((#t)) '((#f))))
      (assert-false  (tn) (eq? '((#t)) '((#t))))
      (assert-false  (tn) (eq? '(1) '(1)))
      (assert-false  (tn) (eq? '(1) '(0)))
      (assert-false  (tn) (eq? '(1 3 5 0 13)
                               '(1 3 5 0 13)))
      (assert-false  (tn) (eq? '(1 3 2 0 13)
                               '(1 3 5 0 13)))
      (assert-false  (tn) (eq? '(1 3 (5 0 13))
                               '(1 3 (5 0 13))))
      (assert-false  (tn) (eq? '(1 3 (2 0 13))
                               '(1 3 (5 0 13))))
      (assert-false  (tn) (eq? '((1)) '((1))))
      (assert-false  (tn) (eq? '((1)) '((0))))
      (assert-false  (tn) (eq? '((1) (3) (5) (0) (13))
                               '((1) (3) (5) (0) (13))))
      (assert-false  (tn) (eq? '((1) (3) (2) (0) (13))
                               '((1) (3) (5) (0) (13))))
      (assert-false  (tn) (eq? '(#\a) '(#\a)))
      (assert-false  (tn) (eq? '(#\a) '(#\b)))
      (assert-false  (tn) (eq? '(#\b) '(#\a)))
      (assert-false  (tn) (eq? '((#\a)) '((#\a))))
      (assert-false  (tn) (eq? '((#\a)) '((#\b))))
      (assert-false  (tn) (eq? '((#\b)) '((#\a))))))

(assert-false  (tn) (eq? (list #f) (list #f)))
(assert-false  (tn) (eq? (list #f) (list #t)))
(assert-false  (tn) (eq? (list #t) (list #f)))
(assert-false  (tn) (eq? (list #t) (list #t)))
(assert-false  (tn) (eq? (list (list #f)) (list (list #f))))
(assert-false  (tn) (eq? (list (list #f)) (list (list #t))))
(assert-false  (tn) (eq? (list (list #t)) (list (list #f))))
(assert-false  (tn) (eq? (list (list #t)) (list (list #t))))
(assert-false  (tn) (eq? (list 1) (list 1)))
(assert-false  (tn) (eq? (list 1) (list 0)))
(assert-false  (tn) (eq? (list 1 3 5 0 13)
                         (list 1 3 5 0 13)))
(assert-false  (tn) (eq? (list 1 3 2 0 13)
                         (list 1 3 5 0 13)))
(assert-false  (tn) (eq? (list 1 3 (list 5 0 13))
                         (list 1 3 (list 5 0 13))))
(assert-false  (tn) (eq? (list 1 3 (list 2 0 13))
                         (list 1 3 (list 5 0 13))))
(assert-false  (tn) (eq? (list (list 1)) (list (list 1))))
(assert-false  (tn) (eq? (list (list 1)) (list (list 0))))
(assert-false  (tn) (eq? (list (list 1) (list 3) (list 5) (list 0) (list 13))
                         (list (list 1) (list 3) (list 5) (list 0) (list 13))))
(assert-false  (tn) (eq? (list (list 1) (list 3) (list 2) (list 0) (list 13))
                         (list (list 1) (list 3) (list 5) (list 0) (list 13))))
(assert-false  (tn) (eq? (list #\a) (list #\a)))
(assert-false  (tn) (eq? (list #\a) (list #\b)))
(assert-false  (tn) (eq? (list #\b) (list #\a)))
(assert-false  (tn) (eq? (list (list #\a)) (list (list #\a))))
(assert-false  (tn) (eq? (list (list #\a)) (list (list #\b))))
(assert-false  (tn) (eq? (list (list #\b)) (list (list #\a))))

(if (provided? "sigscheme")
    (begin
      (assert-false  (tn) (eq? '("") '("")))
      (assert-false  (tn) (eq? '(("")) '((""))))
      (assert-false  (tn) (eq? '("aBc12!")
                               '("aBc12!")))
      (assert-false  (tn) (eq? '("あ0イう12!")
                               '("あ0イう12!")))
      (assert-false  (tn) (eq? '("a" "" "aB1" ("3c" "d") "a")
                               '("a" "" "aB1" ("3c" "d") "a")))
      (assert-false  (tn) (eq? '(("aBc12!"))
                               '(("aBc12!"))))
      (assert-false  (tn) (eq? '(("あ0イう12!"))
                               '(("あ0イう12!"))))))

(assert-false  (tn) (eq? (list "") (list "")))
(assert-false  (tn) (eq? (list (list "")) (list (list ""))))
(assert-false  (tn) (eq? (list "aBc12!")
                         (list "aBc12!")))
(assert-false  (tn) (eq? (list "あ0イう12!")
                         (list "あ0イう12!")))
(assert-false  (tn) (eq? (list "a" "" "aB1" (list "3c" "d") "a")
                         (list "a" "" "aB1" (list "3c" "d") "a")))
(assert-false  (tn) (eq? (list (list "aBc12!"))
                         (list (list "aBc12!"))))
(assert-false  (tn) (eq? (list (list "あ0イう12!"))
                         (list (list "あ0イう12!"))))

(if (provided? "sigscheme")
    (begin
      (assert-false  (tn) (eq? '("aBc123!")
                               '("aBc12!")))
      (assert-false  (tn) (eq? '("あ0イぅ12!")
                               '("あ0イう12!")))
      (assert-false  (tn) (eq? '("a" "" "aB1" ("3c" "e") "a")
                               '("a" "" "aB1" ("3c" "d") "a")))
      (assert-false  (tn) (eq? '(("aBc123!"))
                               '(("aBc12!"))))
      (assert-false  (tn) (eq? '(("あ0イぅ12!"))
                               '(("あ0イう12!"))))))

(assert-false  (tn) (eq? (list "aBc123!")
                         (list "aBc12!")))
(assert-false  (tn) (eq? (list "あ0イぅ12!")
                         (list "あ0イう12!")))
(assert-false  (tn) (eq? (list "a" "" "aB1" (list "3c" "e") "a")
                         (list "a" "" "aB1" (list "3c" "d") "a")))
(assert-false  (tn) (eq? (list (list "aBc123!"))
                         (list (list "aBc12!"))))
(assert-false  (tn) (eq? (list (list "あ0イぅ12!"))
                         (list (list "あ0イう12!"))))

(if (provided? "sigscheme")
    (begin
      (assert-false  (tn)
                     (eq? '(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)
                          '(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)))
      (assert-false  (tn)
                     (eq? '(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)
                          '(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("L")) #t)))
      (assert-false  (tn)
                     (eq? '(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)
                          '(0 #\a "" ("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)))
      (assert-false  (tn)
                     (eq? '(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)
                          '(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" #t)))
      (assert-false  (tn)
                     (eq? '(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" #t)
                          '(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)))))

(assert-false  (tn)
               (eq? (list 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (list -1 #\b '("Ls")) #t)
                    (list 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (list -1 #\b '("Ls")) #t)))
(assert-false  (tn)
               (eq? (list 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (list -1 #\b '("Ls")) #t)
                    (list 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (list -1 #\b '("L")) #t)))
(assert-false  (tn)
               (eq? (list 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (list -1 #\b '("Ls")) #t)
                    (list 0 #\a "" (list "vE" -1 '(#\?))  23 + "aBc" (list -1 #\b '("Ls")) #t)))
(assert-false  (tn)
               (eq? (list 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (list -1 #\b '("Ls")) #t)
                    (list 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" #t)))
(assert-false  (tn)
               (eq? (list 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" #t)
                    (list 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (list -1 #\b '("Ls")) #t)))

(tn "eq? empty vector")
(if (provided? "sigscheme")
    (assert-false  (tn) (eq? '#() '#())))
(assert-false  (tn) (eq? (vector) (vector)))

(let ((v1 '#())
      (v2 (vector)))
  (assert-true   (tn) (eq? v1 v1))
  (assert-true   (tn) (eq? v2 v2))
  (assert-false  (tn) (eq? v1 v2)))

(tn "eq? vector")
(if (provided? "sigscheme")
    (begin
      (assert-false  (tn) (eq? '#(#f) '#(#f)))
      (assert-false  (tn) (eq? '#(#f) '#(#t)))
      (assert-false  (tn) (eq? '#(#t) '#(#f)))
      (assert-false  (tn) (eq? '#(#t) '#(#t)))
      (assert-false  (tn) (eq? '#(#(#f)) '#(#(#f))))
      (assert-false  (tn) (eq? '#(#(#f)) '#(#(#t))))
      (assert-false  (tn) (eq? '#(#(#t)) '#(#(#f))))
      (assert-false  (tn) (eq? '#(#(#t)) '#(#(#t))))
      (assert-false  (tn) (eq? '#(1) '#(1)))
      (assert-false  (tn) (eq? '#(1) '#(0)))
      (assert-false  (tn) (eq? '#(1 3 5 0 13)
                               '#(1 3 5 0 13)))
      (assert-false  (tn) (eq? '#(1 3 2 0 13)
                               '#(1 3 5 0 13)))
      (assert-false  (tn) (eq? '#(1 3 #(5 0 13))
                               '#(1 3 #(5 0 13))))
      (assert-false  (tn) (eq? '#(1 3 #(2 0 13))
                               '#(1 3 #(5 0 13))))
      (assert-false  (tn) (eq? '#(#(1)) '#(#(1))))
      (assert-false  (tn) (eq? '#(#(1)) '#(#(0))))
      (assert-false  (tn) (eq? '#(#(1) #(3) #(5) #(0) #(13))
                               '#(#(1) #(3) #(5) #(0) #(13))))
      (assert-false  (tn) (eq? '#(#(1) #(3) #(2) #(0) #(13))
                               '#(#(1) #(3) #(5) #(0) #(13))))
      (assert-false  (tn) (eq? '#(#\a) '#(#\a)))
      (assert-false  (tn) (eq? '#(#\a) '#(#\b)))
      (assert-false  (tn) (eq? '#(#\b) '#(#\a)))
      (assert-false  (tn) (eq? '#(#(#\a)) '#(#(#\a))))
      (assert-false  (tn) (eq? '#(#(#\a)) '#(#(#\b))))
      (assert-false  (tn) (eq? '#(#(#\b)) '#(#(#\a))))))

(assert-false  (tn) (eq? (vector #f) (vector #f)))
(assert-false  (tn) (eq? (vector #f) (vector #t)))
(assert-false  (tn) (eq? (vector #t) (vector #f)))
(assert-false  (tn) (eq? (vector #t) (vector #t)))
(assert-false  (tn) (eq? (vector (vector #f)) (vector (vector #f))))
(assert-false  (tn) (eq? (vector (vector #f)) (vector (vector #t))))
(assert-false  (tn) (eq? (vector (vector #t)) (vector (vector #f))))
(assert-false  (tn) (eq? (vector (vector #t)) (vector (vector #t))))
(assert-false  (tn) (eq? (vector 1) (vector 1)))
(assert-false  (tn) (eq? (vector 1) (vector 0)))
(assert-false  (tn) (eq? (vector 1 3 5 0 13)
                         (vector 1 3 5 0 13)))
(assert-false  (tn) (eq? (vector 1 3 2 0 13)
                         (vector 1 3 5 0 13)))
(assert-false  (tn) (eq? (vector 1 3 (vector 5 0 13))
                         (vector 1 3 (vector 5 0 13))))
(assert-false  (tn) (eq? (vector 1 3 (vector 2 0 13))
                         (vector 1 3 (vector 5 0 13))))
(assert-false  (tn) (eq? (vector (vector 1)) (vector (vector 1))))
(assert-false  (tn) (eq? (vector (vector 1)) (vector (vector 0))))
(assert-false  (tn) (eq? (vector (vector 1) (vector 3) (vector 5) (vector 0) (vector 13))
                         (vector (vector 1) (vector 3) (vector 5) (vector 0) (vector 13))))
(assert-false  (tn) (eq? (vector (vector 1) (vector 3) (vector 2) (vector 0) (vector 13))
                         (vector (vector 1) (vector 3) (vector 5) (vector 0) (vector 13))))
(assert-false  (tn) (eq? (vector #\a) (vector #\a)))
(assert-false  (tn) (eq? (vector #\a) (vector #\b)))
(assert-false  (tn) (eq? (vector #\b) (vector #\a)))
(assert-false  (tn) (eq? (vector (vector #\a)) (vector (vector #\a))))
(assert-false  (tn) (eq? (vector (vector #\a)) (vector (vector #\b))))
(assert-false  (tn) (eq? (vector (vector #\b)) (vector (vector #\a))))

(if (provided? "sigscheme")
    (begin
      (assert-false  (tn) (eq? '#("") '#("")))
      (assert-false  (tn) (eq? '#(#("")) '#(#(""))))
      (assert-false  (tn) (eq? '#("aBc12!")
                               '#("aBc12!")))
      (assert-false  (tn) (eq? '#("あ0イう12!")
                               '#("あ0イう12!")))
      (assert-false  (tn) (eq? '#("a" "" "aB1" #("3c" "d") "a")
                               '#("a" "" "aB1" #("3c" "d") "a")))
      (assert-false  (tn) (eq? '#(#("aBc12!"))
                               '#(#("aBc12!"))))
      (assert-false  (tn) (eq? '#(#("あ0イう12!"))
                               '#(#("あ0イう12!"))))))

(assert-false  (tn) (eq? (vector "") (vector "")))
(assert-false  (tn) (eq? (vector (vector "")) (vector (vector ""))))
(assert-false  (tn) (eq? (vector "aBc12!")
                         (vector "aBc12!")))
(assert-false  (tn) (eq? (vector "あ0イう12!")
                         (vector "あ0イう12!")))
(assert-false  (tn) (eq? (vector "a" "" "aB1" (vector "3c" "d") "a")
                         (vector "a" "" "aB1" (vector "3c" "d") "a")))
(assert-false  (tn) (eq? (vector (vector "aBc12!"))
                         (vector (vector "aBc12!"))))
(assert-false  (tn) (eq? (vector (vector "あ0イう12!"))
                         (vector (vector "あ0イう12!"))))

(if (provided? "sigscheme")
    (begin
      (assert-false  (tn) (eq? '#("aBc123!")
                               '#("aBc12!")))
      (assert-false  (tn) (eq? '#("あ0イぅ12!")
                               '#("あ0イう12!")))
      (assert-false  (tn) (eq? '#("a" "" "aB1" #("3c" "e") "a")
                               '#("a" "" "aB1" #("3c" "d") "a")))
      (assert-false  (tn) (eq? '#(#("aBc123!"))
                               '#(#("aBc12!"))))
      (assert-false  (tn) (eq? '#(#("あ0イぅ12!"))
                               '#(#("あ0イう12!"))))))

(assert-false  (tn) (eq? (vector "aBc123!")
                         (vector "aBc12!")))
(assert-false  (tn) (eq? (vector "あ0イぅ12!")
                         (vector "あ0イう12!")))
(assert-false  (tn) (eq? (vector "a" "" "aB1" (vector "3c" "e") "a")
                         (vector "a" "" "aB1" (vector "3c" "d") "a")))
(assert-false  (tn) (eq? (vector (vector "aBc123!"))
                         (vector (vector "aBc12!"))))
(assert-false  (tn) (eq? (vector (vector "あ0イぅ12!"))
                         (vector (vector "あ0イう12!"))))

(if (provided? "sigscheme")
    (begin
      (assert-false  (tn)
                     (eq? '#(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)
                          '#(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)))
      (assert-false  (tn)
                     (eq? '#(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)
                          '#(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("L")) #t)))
      (assert-false  (tn)
                     (eq? '#(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)
                          '#(0 #\a "" ("vE" -1 (#\?))  23 + "aBc" (-1 #\b ("Ls")) #t)))
      (assert-false  (tn)
                     (eq? '#(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)
                          '#(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" #t)))
      (assert-false  (tn)
                     (eq? '#(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" #t)
                          '#(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)))))

(assert-false  (tn)
               (eq? (vector 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (vector -1 #\b '("Ls")) #t)
                    (vector 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (vector -1 #\b '("Ls")) #t)))
(assert-false  (tn)
               (eq? (vector 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (vector -1 #\b '("Ls")) #t)
                    (vector 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (vector -1 #\b '("L")) #t)))
(assert-false  (tn)
               (eq? (vector 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (vector -1 #\b '("Ls")) #t)
                    (vector 0 #\a "" (list "vE" -1 '(#\?))   23 + "aBc" (vector -1 #\b '("Ls")) #t)))
(assert-false  (tn)
               (eq? (vector 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (vector -1 #\b '("Ls")) #t)
                    (vector 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" #t)))
(assert-false  (tn)
               (eq? (vector 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" #t)
                    (vector 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (vector -1 #\b '("Ls")) #t)))


(total-report)
