#! /usr/bin/env sscm -C UTF-8
;; -*- buffer-file-coding-system: utf-8 -*-

;;  Filename : test-eqv.scm
;;  About    : unit tests for eqv?
;;
;;  Copyright (C) 2006 YAMAMOTO Kengo <yamaken AT bp.iij4u.or.jp>
;;
;;  All rights reserved.
;;
;;  Redistribution and use in source and binary forms, with or without
;;  modification, are permitted provided that the following conditions
;;  are met:
;;
;;  1. Redistributions of source code must retain the above copyright
;;     notice, this list of conditions and the following disclaimer.
;;  2. Redistributions in binary form must reproduce the above copyright
;;     notice, this list of conditions and the following disclaimer in the
;;     documentation and/or other materials provided with the distribution.
;;  3. Neither the name of authors nor the names of its contributors
;;     may be used to endorse or promote products derived from this software
;;     without specific prior written permission.
;;
;;  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS ``AS
;;  IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
;;  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
;;  PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR
;;  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
;;  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
;;  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
;;  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
;;  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
;;  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
;;  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

(load "test/unittest.scm")

(define tn test-name)

(tn "eqv? invalid form")
(assert-error  (tn) (lambda () (eqv?)))
(assert-error  (tn) (lambda () (eqv? #f)))
(assert-error  (tn) (lambda () (eqv? #f #f #f)))

(tn "eqv? different types")
(assert-false  (tn) (eqv? 1 #\1))
(assert-false  (tn) (eqv? #\1 "1"))
(assert-false  (tn) (eqv? #\1 '("1")))
(assert-false  (tn) (eqv? '#("1") '("1")))

(tn "eqv? boolean")
(assert-true   (tn) (eqv? #f #f))
(assert-false  (tn) (eqv? #f #t))
(assert-false  (tn) (eqv? #t #f))
(assert-true   (tn) (eqv? #t #t))

(tn "eqv? null")
(assert-true   (tn) (eqv? '() '()))
(if (and (provided? "sigscheme")
         (provided? "siod-bugs"))
    (begin
      (assert-true   (tn) (eqv? #f '()))
      (assert-true   (tn) (eqv? '() #f)))
    (begin
      (assert-false  (tn) (eqv? #f '()))
      (assert-false  (tn) (eqv? '() #f))))
(if (symbol-bound? 'vector?)
    (begin
      (assert-false  (tn) (eqv? '() '#()))
      (assert-false  (tn) (eqv? '#() '()))))

(tn "eqv? #<eof>")
(if (provided? "sigscheme")
    (begin
      (assert-true   (tn) (eqv? (eof) (eof)))
      (assert-false  (tn) (eqv? (eof) (undef)))
      (assert-false  (tn) (eqv? (undef) (eof)))
      (assert-false  (tn) (eqv? '() (eof)))
      (assert-false  (tn) (eqv? (eof) '()))
      (assert-false  (tn) (eqv? #f (eof)))
      (assert-false  (tn) (eqv? (eof) #f))))

(tn "eqv? #<undef>")
(if (provided? "sigscheme")
    (begin
      (assert-true   (tn) (eqv? (undef) (undef)))
      (assert-false  (tn) (eqv? (eof) (undef)))
      (assert-false  (tn) (eqv? (undef) (eof)))
      (assert-false  (tn) (eqv? '() (undef)))
      (assert-false  (tn) (eqv? (undef) '()))
      (assert-false  (tn) (eqv? #f (undef)))
      (assert-false  (tn) (eqv? (undef) #f))))

(tn "eqv? integer")
(assert-true   (tn) (eqv? 0 0))
(assert-true   (tn) (eqv? 1 1))
(assert-true   (tn) (eqv? 3 3))
(assert-true   (tn) (eqv? -1 -1))
(assert-true   (tn) (eqv? -3 -3))

(assert-false  (tn) (eqv? 0 1))
(assert-false  (tn) (eqv? 1 0))
(assert-false  (tn) (eqv? 1 3))
(assert-false  (tn) (eqv? 3 1))
(assert-false  (tn) (eqv? -1 1))
(assert-false  (tn) (eqv? 1 -1))
(assert-false  (tn) (eqv? -3 3))
(assert-false  (tn) (eqv? 3 -3))
(assert-false  (tn) (eqv? -1 -3))
(assert-false  (tn) (eqv? -3 -1))

(tn "eqv? symbol")
(assert-true   (tn) (eqv? 'symbol 'symbol))
(assert-false  (tn) (eqv? 'symbol1 'symbol2))
(if (and (provided? "sigscheme")
         (provided? "strict-r5rs"))
    (begin
      (assert-true   (tn) (eqv? 'symbol 'SYMBOL))
      (assert-true   (tn) (eqv? 'SYMBOL 'symbol))
      (assert-true   (tn) (eqv? 'symbol 'Symbol))
      (assert-true   (tn) (eqv? 'Symbol 'symbol))
      (assert-true   (tn) (eqv? 'symbol 'syMBoL))
      (assert-true   (tn) (eqv? 'syMBoL 'symbol)))
    (begin
      (assert-false  (tn) (eqv? 'symbol 'SYMBOL))
      (assert-false  (tn) (eqv? 'SYMBOL 'symbol))
      (assert-false  (tn) (eqv? 'symbol 'Symbol))
      (assert-false  (tn) (eqv? 'Symbol 'symbol))
      (assert-false  (tn) (eqv? 'symbol 'syMBoL))
      (assert-false  (tn) (eqv? 'syMBoL 'symbol))))

(tn "eqv? singlebyte char")
(assert-true   (tn) (eqv? #\a #\a))
(assert-false  (tn) (eqv? #\a #\b))
(assert-false  (tn) (eqv? #\b #\a))
(assert-true   (tn) (eqv? #\b #\b))

(let ((c1 #\a)
      (c2 #\b))
  (assert-true   (tn) (eqv? c1 c1))
  (assert-true   (tn) (eqv? c2 c2)))

(tn "eqv? multibyte char")
(assert-true   (tn) (eqv? #\あ #\あ))
(assert-false  (tn) (eqv? #\あ #\い))
(assert-false  (tn) (eqv? #\い #\あ))
(assert-true   (tn) (eqv? #\い #\い))

(let ((c1 #\あ)
      (c2 #\い))
  (assert-true   (tn) (eqv? c1 c1))
  (assert-true   (tn) (eqv? c2 c2)))

(tn "eqv? singlebyte string")
(if (provided? "sigscheme")
    (begin
      (assert-false  (tn) (eqv? "" ""))
      (assert-false  (tn) (eqv? "a" "a"))
      (assert-false  (tn) (eqv? "b" "b"))
      (assert-false  (tn) (eqv? "aBc12!" "aBc12!"))))
(let ((s1 "")
      (s2 "a")
      (s3 "b")
      (s4 "aBc12!"))
  (assert-true   (tn) (eqv? s1 s1))
  (assert-true   (tn) (eqv? s2 s2))
  (assert-true   (tn) (eqv? s3 s3))
  (assert-true   (tn) (eqv? s4 s4)))
(assert-false  (tn) (eqv? "" "a"))
(assert-false  (tn) (eqv? "a" ""))
(assert-false  (tn) (eqv? "a" "b"))
(assert-false  (tn) (eqv? "b" "a"))
(assert-false  (tn) (eqv? "a" "A"))
(assert-false  (tn) (eqv? "A" "a"))
(assert-false  (tn) (eqv? "aBc123!" "aBc12!"))
(assert-false  (tn) (eqv? "aBc12!" "aBc123!"))

(tn "eqv? multibyte string")
(if (provided? "sigscheme")
    (begin
      (assert-false  (tn) (eqv? "あ" "あ"))
      (assert-false  (tn) (eqv? "い" "い"))
      (assert-false  (tn) (eqv? "あ0イう12!" "あ0イう12!"))))
(let ((s1 "あ")
      (s2 "い")
      (s3 "あ0イう12!"))
  (assert-true   (tn) (eqv? s1 s1))
  (assert-true   (tn) (eqv? s2 s2))
  (assert-true   (tn) (eqv? s3 s3)))
(assert-false  (tn) (eqv? "" "あ"))
(assert-false  (tn) (eqv? "あ" ""))
(assert-false  (tn) (eqv? "あ" "い"))
(assert-false  (tn) (eqv? "い" "あ"))
(assert-false  (tn) (eqv? "あ" "ア"))
(assert-false  (tn) (eqv? "ア" "あ"))
(assert-false  (tn) (eqv? "あ0イうぇ12!" "あ0イう12!"))
(assert-false  (tn) (eqv? "あ0イう12!" "あ0イうぇ12!"))

(tn "eqv? procedure")
(assert-true   (tn) (eqv? + +))
(assert-false  (tn) (eqv? + -))
(assert-false  (tn) (eqv? - +))
(assert-true   (tn) (eqv? - -))
(let ((plus +))
  (assert-true   (tn) (eqv? + plus))
  (assert-true   (tn) (eqv? plus +))
  (assert-true   (tn) (eqv? plus plus)))

(tn "eqv? syntax")
(assert-true   (tn) (eqv? if if))
(assert-false  (tn) (eqv? if set!))
(assert-false  (tn) (eqv? set! if))
(assert-true   (tn) (eqv? set! set!))
;; (define syntax if) is an invalid form

(tn "eqv? macro")
(if (symbol-bound? 'let-syntax)
    (let-syntax ((macro1 (syntax-rules ()
                           ((_) 'macro1-expanded)))
                 (macro2 (syntax-rules ()
                           ((_) 'macro2-expanded))))
      (assert-true   (tn) (eqv? macro1 macro1))
      (assert-false  (tn) (eqv? macro2 macro1))
      (assert-false  (tn) (eqv? macro1 macro2))
      (assert-true   (tn) (eqv? macro2 macro2))))

(tn "eqv? closure")
(let ((closure (lambda () #t)))
  (assert-true   (tn) (eqv? closure closure))
  (if (provided? "sigscheme")
      (begin
        (assert-false  (tn) (eqv? closure (lambda () #t)))
        (assert-false  (tn) (eqv? (lambda () #t) closure))
        (assert-false  (tn) (eqv? (lambda () #t) (lambda () #t))))))

(tn "eqv? stateful closure")
(let ((stateful (lambda ()
                  (let ((state 0))
                    (lambda ()
                      (set! state (+ state 1))
                      state)))))
  (assert-true   (tn) (eqv? stateful stateful))
  (assert-false  (tn) (eqv? (stateful) (stateful))))

(let ((may-be-optimized-out (lambda ()
                              (let ((state 0))
                                (lambda ()
                                  (set! state (+ state 1))
                                  0)))))
  (assert-true   (tn) (eqv? may-be-optimized-out may-be-optimized-out))
  (if (provided? "sigscheme")
      (assert-false (tn) (eqv? (may-be-optimized-out) (may-be-optimized-out)))))

(letrec ((may-be-unified1 (lambda ()
                            (if (eqv? may-be-unified1
                                      may-be-unified2)
                                'optimized-out
                                'not-unified1)))
         (may-be-unified2 (lambda ()
                            (if (eqv? may-be-unified1
                                      may-be-unified2)
                                'optimized-out
                                'not-unified2))))
  (if (provided? "sigscheme")
      (begin
        (assert-false  (tn) (eqv? may-be-unified1 may-be-unified2))
        (assert-false  (tn) (eqv? (may-be-unified1) (may-be-unified2))))
      (begin
        ;; other implementations may pass this
        ;;(assert-true   (tn) (eqv? may-be-unified1 may-be-unified2))
        ;;(assert-true   (tn) (eqv? (may-be-unified1) (may-be-unified2)))
        )))

(tn "eqv? continuation")
(call-with-current-continuation
 (lambda (k1)
   (call-with-current-continuation
    (lambda (k2)
      (assert-true   (tn) (eqv? k1 k1))
      (assert-false  (tn) (eqv? k1 k2))
      (assert-false  (tn) (eqv? k2 k1))
      (assert-true   (tn) (eqv? k2 k2))
      (let ((cont k1))
        (assert-true   (tn) (eqv? cont cont))
        (assert-true   (tn) (eqv? cont k1))
        (assert-true   (tn) (eqv? k1 cont))
        (assert-false  (tn) (eqv? cont k2))
        (assert-false  (tn) (eqv? k2 cont)))))))

(tn "eqv? port")
(assert-true   (tn) (eqv? (current-output-port) (current-output-port)))
(assert-false  (tn) (eqv? (current-input-port) (current-output-port)))
(assert-false  (tn) (eqv? (current-output-port) (current-input-port)))
(assert-true   (tn) (eqv? (current-input-port) (current-input-port)))
(let ((port (current-input-port)))
  (assert-true   (tn) (eqv? port port))
  (assert-true   (tn) (eqv? (current-input-port) port))
  (assert-true   (tn) (eqv? port (current-input-port)))
  (assert-false  (tn) (eqv? (current-output-port) port))
  (assert-false  (tn) (eqv? port (current-output-port))))

(tn "eqv? pair")
(if (provided? "sigscheme")
    (begin
      (assert-false  (tn) (eqv? '(#t . #t) '(#t . #t)))
      (assert-false  (tn) (eqv? '(#f . #t) '(#f . #t)))
      (assert-false  (tn) (eqv? '(#t . #f) '(#t . #f)))
      (assert-false  (tn) (eqv? '(#f . #t) '(#t . #f)))
      (assert-false  (tn) (eqv? '(#\a . #\a) '(#\a . #\a)))
      (assert-false  (tn) (eqv? '(#\a . #\b) '(#\a . #\b)))
      (assert-false  (tn) (eqv? '(#\b . #\a) '(#\b . #\a)))
      (assert-false  (tn) (eqv? '(#\a . #\b) '(#\b . #\a)))
      (assert-false  (tn) (eqv? '("a" . "a") '("a" . "a")))
      (assert-false  (tn) (eqv? '("a" . "b") '("a" . "b")))
      (assert-false  (tn) (eqv? '("b" . "a") '("b" . "a")))
      (assert-false  (tn) (eqv? '("a" . "b") '("b" . "a")))))

(assert-false  (tn) (eqv? (cons #t #t) (cons #t #t)))
(assert-false  (tn) (eqv? (cons #f #t) (cons #f #t)))
(assert-false  (tn) (eqv? (cons #t #f) (cons #t #f)))
(assert-false  (tn) (eqv? (cons #f #t) (cons #t #f)))
(assert-false  (tn) (eqv? (cons #\a #\a) (cons #\a #\a)))
(assert-false  (tn) (eqv? (cons #\a #\b) (cons #\a #\b)))
(assert-false  (tn) (eqv? (cons #\b #\a) (cons #\b #\a)))
(assert-false  (tn) (eqv? (cons #\a #\b) (cons #\b #\a)))
(assert-false  (tn) (eqv? (cons "a" "a") (cons "a" "a")))
(assert-false  (tn) (eqv? (cons "a" "b") (cons "a" "b")))
(assert-false  (tn) (eqv? (cons "b" "a") (cons "b" "a")))
(assert-false  (tn) (eqv? (cons "a" "b") (cons "b" "a")))

(tn "eqv? list")
(if (provided? "sigscheme")
    (begin
      (assert-false  (tn) (eqv? '(#f) '(#f)))
      (assert-false  (tn) (eqv? '(#f) '(#t)))
      (assert-false  (tn) (eqv? '(#t) '(#f)))
      (assert-false  (tn) (eqv? '(#t) '(#t)))
      (assert-false  (tn) (eqv? '((#f)) '((#f))))
      (assert-false  (tn) (eqv? '((#f)) '((#t))))
      (assert-false  (tn) (eqv? '((#t)) '((#f))))
      (assert-false  (tn) (eqv? '((#t)) '((#t))))
      (assert-false  (tn) (eqv? '(1) '(1)))
      (assert-false  (tn) (eqv? '(1) '(0)))
      (assert-false  (tn) (eqv? '(1 3 5 0 13)
                                '(1 3 5 0 13)))
      (assert-false  (tn) (eqv? '(1 3 2 0 13)
                                '(1 3 5 0 13)))
      (assert-false  (tn) (eqv? '(1 3 (5 0 13))
                                '(1 3 (5 0 13))))
      (assert-false  (tn) (eqv? '(1 3 (2 0 13))
                                '(1 3 (5 0 13))))
      (assert-false  (tn) (eqv? '((1)) '((1))))
      (assert-false  (tn) (eqv? '((1)) '((0))))
      (assert-false  (tn) (eqv? '((1) (3) (5) (0) (13))
                                '((1) (3) (5) (0) (13))))
      (assert-false  (tn) (eqv? '((1) (3) (2) (0) (13))
                                '((1) (3) (5) (0) (13))))
      (assert-false  (tn) (eqv? '(#\a) '(#\a)))
      (assert-false  (tn) (eqv? '(#\a) '(#\b)))
      (assert-false  (tn) (eqv? '(#\b) '(#\a)))
      (assert-false  (tn) (eqv? '((#\a)) '((#\a))))
      (assert-false  (tn) (eqv? '((#\a)) '((#\b))))
      (assert-false  (tn) (eqv? '((#\b)) '((#\a))))))

(assert-false  (tn) (eqv? (list #f) (list #f)))
(assert-false  (tn) (eqv? (list #f) (list #t)))
(assert-false  (tn) (eqv? (list #t) (list #f)))
(assert-false  (tn) (eqv? (list #t) (list #t)))
(assert-false  (tn) (eqv? (list (list #f)) (list (list #f))))
(assert-false  (tn) (eqv? (list (list #f)) (list (list #t))))
(assert-false  (tn) (eqv? (list (list #t)) (list (list #f))))
(assert-false  (tn) (eqv? (list (list #t)) (list (list #t))))
(assert-false  (tn) (eqv? (list 1) (list 1)))
(assert-false  (tn) (eqv? (list 1) (list 0)))
(assert-false  (tn) (eqv? (list 1 3 5 0 13)
                          (list 1 3 5 0 13)))
(assert-false  (tn) (eqv? (list 1 3 2 0 13)
                          (list 1 3 5 0 13)))
(assert-false  (tn) (eqv? (list 1 3 (list 5 0 13))
                          (list 1 3 (list 5 0 13))))
(assert-false  (tn) (eqv? (list 1 3 (list 2 0 13))
                          (list 1 3 (list 5 0 13))))
(assert-false  (tn) (eqv? (list (list 1)) (list (list 1))))
(assert-false  (tn) (eqv? (list (list 1)) (list (list 0))))
(assert-false  (tn) (eqv? (list (list 1) (list 3) (list 5) (list 0) (list 13))
                          (list (list 1) (list 3) (list 5) (list 0) (list 13))))
(assert-false  (tn) (eqv? (list (list 1) (list 3) (list 2) (list 0) (list 13))
                          (list (list 1) (list 3) (list 5) (list 0) (list 13))))
(assert-false  (tn) (eqv? (list #\a) (list #\a)))
(assert-false  (tn) (eqv? (list #\a) (list #\b)))
(assert-false  (tn) (eqv? (list #\b) (list #\a)))
(assert-false  (tn) (eqv? (list (list #\a)) (list (list #\a))))
(assert-false  (tn) (eqv? (list (list #\a)) (list (list #\b))))
(assert-false  (tn) (eqv? (list (list #\b)) (list (list #\a))))

(if (provided? "sigscheme")
    (begin
      (assert-false  (tn) (eqv? '("") '("")))
      (assert-false  (tn) (eqv? '(("")) '((""))))
      (assert-false  (tn) (eqv? '("aBc12!")
                                '("aBc12!")))
      (assert-false  (tn) (eqv? '("あ0イう12!")
                                '("あ0イう12!")))
      (assert-false  (tn) (eqv? '("a" "" "aB1" ("3c" "d") "a")
                                '("a" "" "aB1" ("3c" "d") "a")))
      (assert-false  (tn) (eqv? '(("aBc12!"))
                                '(("aBc12!"))))
      (assert-false  (tn) (eqv? '(("あ0イう12!"))
                                '(("あ0イう12!"))))))

(assert-false  (tn) (eqv? (list "") (list "")))
(assert-false  (tn) (eqv? (list (list "")) (list (list ""))))
(assert-false  (tn) (eqv? (list "aBc12!")
                          (list "aBc12!")))
(assert-false  (tn) (eqv? (list "あ0イう12!")
                          (list "あ0イう12!")))
(assert-false  (tn) (eqv? (list "a" "" "aB1" (list "3c" "d") "a")
                          (list "a" "" "aB1" (list "3c" "d") "a")))
(assert-false  (tn) (eqv? (list (list "aBc12!"))
                          (list (list "aBc12!"))))
(assert-false  (tn) (eqv? (list (list "あ0イう12!"))
                          (list (list "あ0イう12!"))))

(if (provided? "sigscheme")
    (begin
      (assert-false  (tn) (eqv? '("aBc123!")
                                '("aBc12!")))
      (assert-false  (tn) (eqv? '("あ0イぅ12!")
                                '("あ0イう12!")))
      (assert-false  (tn) (eqv? '("a" "" "aB1" ("3c" "e") "a")
                                '("a" "" "aB1" ("3c" "d") "a")))
      (assert-false  (tn) (eqv? '(("aBc123!"))
                                '(("aBc12!"))))
      (assert-false  (tn) (eqv? '(("あ0イぅ12!"))
                                '(("あ0イう12!"))))))

(assert-false  (tn) (eqv? (list "aBc123!")
                          (list "aBc12!")))
(assert-false  (tn) (eqv? (list "あ0イぅ12!")
                          (list "あ0イう12!")))
(assert-false  (tn) (eqv? (list "a" "" "aB1" (list "3c" "e") "a")
                          (list "a" "" "aB1" (list "3c" "d") "a")))
(assert-false  (tn) (eqv? (list (list "aBc123!"))
                          (list (list "aBc12!"))))
(assert-false  (tn) (eqv? (list (list "あ0イぅ12!"))
                          (list (list "あ0イう12!"))))

(if (provided? "sigscheme")
    (begin
      (assert-false  (tn)
                     (eqv? '(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)
                           '(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)))
      (assert-false  (tn)
                     (eqv? '(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)
                           '(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("L")) #t)))
      (assert-false  (tn)
                     (eqv? '(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)
                           '(0 #\a "" ("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)))
      (assert-false  (tn)
                     (eqv? '(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)
                           '(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" #t)))
      (assert-false  (tn)
                     (eqv? '(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" #t)
                           '(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)))))

(assert-false  (tn)
               (eqv? (list 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (list -1 #\b '("Ls")) #t)
                     (list 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (list -1 #\b '("Ls")) #t)))
(assert-false  (tn)
               (eqv? (list 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (list -1 #\b '("Ls")) #t)
                     (list 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (list -1 #\b '("L")) #t)))
(assert-false  (tn)
               (eqv? (list 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (list -1 #\b '("Ls")) #t)
                     (list 0 #\a "" (list "vE" -1 '(#\?))   23 + "aBc" (list -1 #\b '("Ls")) #t)))
(assert-false  (tn)
               (eqv? (list 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (list -1 #\b '("Ls")) #t)
                     (list 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" #t)))
(assert-false  (tn)
               (eqv? (list 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" #t)
                     (list 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (list -1 #\b '("Ls")) #t)))

(tn "eqv? empty vector")
(if (provided? "sigscheme")
    (assert-false  (tn) (eqv? '#() '#())))
(assert-false  (tn) (eqv? (vector) (vector)))

(let ((v1 '#())
      (v2 (vector)))
  (assert-true   (tn) (eqv? v1 v1))
  (assert-true   (tn) (eqv? v2 v2))
  (assert-false  (tn) (eqv? v1 v2)))

(tn "eqv? vector")
(if (provided? "sigscheme")
    (begin
      (assert-false  (tn) (eqv? '#(#f) '#(#f)))
      (assert-false  (tn) (eqv? '#(#f) '#(#t)))
      (assert-false  (tn) (eqv? '#(#t) '#(#f)))
      (assert-false  (tn) (eqv? '#(#t) '#(#t)))
      (assert-false  (tn) (eqv? '#(#(#f)) '#(#(#f))))
      (assert-false  (tn) (eqv? '#(#(#f)) '#(#(#t))))
      (assert-false  (tn) (eqv? '#(#(#t)) '#(#(#f))))
      (assert-false  (tn) (eqv? '#(#(#t)) '#(#(#t))))
      (assert-false  (tn) (eqv? '#(1) '#(1)))
      (assert-false  (tn) (eqv? '#(1) '#(0)))
      (assert-false  (tn) (eqv? '#(1 3 5 0 13)
                                '#(1 3 5 0 13)))
      (assert-false  (tn) (eqv? '#(1 3 2 0 13)
                                '#(1 3 5 0 13)))
      (assert-false  (tn) (eqv? '#(1 3 #(5 0 13))
                                '#(1 3 #(5 0 13))))
      (assert-false  (tn) (eqv? '#(1 3 #(2 0 13))
                                '#(1 3 #(5 0 13))))
      (assert-false  (tn) (eqv? '#(#(1)) '#(#(1))))
      (assert-false  (tn) (eqv? '#(#(1)) '#(#(0))))
      (assert-false  (tn) (eqv? '#(#(1) #(3) #(5) #(0) #(13))
                                '#(#(1) #(3) #(5) #(0) #(13))))
      (assert-false  (tn) (eqv? '#(#(1) #(3) #(2) #(0) #(13))
                                '#(#(1) #(3) #(5) #(0) #(13))))
      (assert-false  (tn) (eqv? '#(#\a) '#(#\a)))
      (assert-false  (tn) (eqv? '#(#\a) '#(#\b)))
      (assert-false  (tn) (eqv? '#(#\b) '#(#\a)))
      (assert-false  (tn) (eqv? '#(#(#\a)) '#(#(#\a))))
      (assert-false  (tn) (eqv? '#(#(#\a)) '#(#(#\b))))
      (assert-false  (tn) (eqv? '#(#(#\b)) '#(#(#\a))))))

(assert-false  (tn) (eqv? (vector #f) (vector #f)))
(assert-false  (tn) (eqv? (vector #f) (vector #t)))
(assert-false  (tn) (eqv? (vector #t) (vector #f)))
(assert-false  (tn) (eqv? (vector #t) (vector #t)))
(assert-false  (tn) (eqv? (vector (vector #f)) (vector (vector #f))))
(assert-false  (tn) (eqv? (vector (vector #f)) (vector (vector #t))))
(assert-false  (tn) (eqv? (vector (vector #t)) (vector (vector #f))))
(assert-false  (tn) (eqv? (vector (vector #t)) (vector (vector #t))))
(assert-false  (tn) (eqv? (vector 1) (vector 1)))
(assert-false  (tn) (eqv? (vector 1) (vector 0)))
(assert-false  (tn) (eqv? (vector 1 3 5 0 13)
                          (vector 1 3 5 0 13)))
(assert-false  (tn) (eqv? (vector 1 3 2 0 13)
                          (vector 1 3 5 0 13)))
(assert-false  (tn) (eqv? (vector 1 3 (vector 5 0 13))
                          (vector 1 3 (vector 5 0 13))))
(assert-false  (tn) (eqv? (vector 1 3 (vector 2 0 13))
                          (vector 1 3 (vector 5 0 13))))
(assert-false  (tn) (eqv? (vector (vector 1)) (vector (vector 1))))
(assert-false  (tn) (eqv? (vector (vector 1)) (vector (vector 0))))
(assert-false  (tn) (eqv? (vector (vector 1) (vector 3) (vector 5) (vector 0) (vector 13))
                          (vector (vector 1) (vector 3) (vector 5) (vector 0) (vector 13))))
(assert-false  (tn) (eqv? (vector (vector 1) (vector 3) (vector 2) (vector 0) (vector 13))
                          (vector (vector 1) (vector 3) (vector 5) (vector 0) (vector 13))))
(assert-false  (tn) (eqv? (vector #\a) (vector #\a)))
(assert-false  (tn) (eqv? (vector #\a) (vector #\b)))
(assert-false  (tn) (eqv? (vector #\b) (vector #\a)))
(assert-false  (tn) (eqv? (vector (vector #\a)) (vector (vector #\a))))
(assert-false  (tn) (eqv? (vector (vector #\a)) (vector (vector #\b))))
(assert-false  (tn) (eqv? (vector (vector #\b)) (vector (vector #\a))))

(if (provided? "sigscheme")
    (begin
      (assert-false  (tn) (eqv? '#("") '#("")))
      (assert-false  (tn) (eqv? '#(#("")) '#(#(""))))
      (assert-false  (tn) (eqv? '#("aBc12!")
                                '#("aBc12!")))
      (assert-false  (tn) (eqv? '#("あ0イう12!")
                                '#("あ0イう12!")))
      (assert-false  (tn) (eqv? '#("a" "" "aB1" #("3c" "d") "a")
                                '#("a" "" "aB1" #("3c" "d") "a")))
      (assert-false  (tn) (eqv? '#(#("aBc12!"))
                                '#(#("aBc12!"))))
      (assert-false  (tn) (eqv? '#(#("あ0イう12!"))
                                '#(#("あ0イう12!"))))))

(assert-false  (tn) (eqv? (vector "") (vector "")))
(assert-false  (tn) (eqv? (vector (vector "")) (vector (vector ""))))
(assert-false  (tn) (eqv? (vector "aBc12!")
                          (vector "aBc12!")))
(assert-false  (tn) (eqv? (vector "あ0イう12!")
                          (vector "あ0イう12!")))
(assert-false  (tn) (eqv? (vector "a" "" "aB1" (vector "3c" "d") "a")
                          (vector "a" "" "aB1" (vector "3c" "d") "a")))
(assert-false  (tn) (eqv? (vector (vector "aBc12!"))
                          (vector (vector "aBc12!"))))
(assert-false  (tn) (eqv? (vector (vector "あ0イう12!"))
                          (vector (vector "あ0イう12!"))))

(if (provided? "sigscheme")
    (begin
      (assert-false  (tn) (eqv? '#("aBc123!")
                                '#("aBc12!")))
      (assert-false  (tn) (eqv? '#("あ0イぅ12!")
                                '#("あ0イう12!")))
      (assert-false  (tn) (eqv? '#("a" "" "aB1" #("3c" "e") "a")
                                '#("a" "" "aB1" #("3c" "d") "a")))
      (assert-false  (tn) (eqv? '#(#("aBc123!"))
                                '#(#("aBc12!"))))
      (assert-false  (tn) (eqv? '#(#("あ0イぅ12!"))
                                '#(#("あ0イう12!"))))))

(assert-false  (tn) (eqv? (vector "aBc123!")
                          (vector "aBc12!")))
(assert-false  (tn) (eqv? (vector "あ0イぅ12!")
                          (vector "あ0イう12!")))
(assert-false  (tn) (eqv? (vector "a" "" "aB1" (vector "3c" "e") "a")
                          (vector "a" "" "aB1" (vector "3c" "d") "a")))
(assert-false  (tn) (eqv? (vector (vector "aBc123!"))
                          (vector (vector "aBc12!"))))
(assert-false  (tn) (eqv? (vector (vector "あ0イぅ12!"))
                          (vector (vector "あ0イう12!"))))

(if (provided? "sigscheme")
    (begin
      (assert-false  (tn)
                     (eqv? '#(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)
                           '#(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)))
      (assert-false  (tn)
                     (eqv? '#(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)
                           '#(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("L")) #t)))
      (assert-false  (tn)
                     (eqv? '#(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)
                           '#(0 #\a "" ("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)))
      (assert-false  (tn)
                     (eqv? '#(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)
                           '#(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" #t)))
      (assert-false  (tn)
                     (eqv? '#(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" #t)
                           '#(0 #\a "" #("vE" -1 (#\?)) 23 + "aBc" (-1 #\b ("Ls")) #t)))))

(assert-false  (tn)
               (eqv? (vector 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (vector -1 #\b '("Ls")) #t)
                     (vector 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (vector -1 #\b '("Ls")) #t)))
(assert-false  (tn)
               (eqv? (vector 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (vector -1 #\b '("Ls")) #t)
                     (vector 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (vector -1 #\b '("L")) #t)))
(assert-false  (tn)
               (eqv? (vector 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (vector -1 #\b '("Ls")) #t)
                     (vector 0 #\a "" (list "vE" -1 '(#\?))   23 + "aBc" (vector -1 #\b '("Ls")) #t)))
(assert-false  (tn)
               (eqv? (vector 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (vector -1 #\b '("Ls")) #t)
                     (vector 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" #t)))
(assert-false  (tn)
               (eqv? (vector 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" #t)
                     (vector 0 #\a "" (vector "vE" -1 '(#\?)) 23 + "aBc" (vector -1 #\b '("Ls")) #t)))


(total-report)
