;;  FileName : test-char-cmp.scm
;;  About    : unit test for R5RS char
;;
;;  Copyright (C) 2006 YamaKen <yamaken AT bp.iij4u.or.jp>
;;
;;  All rights reserved.
;;
;;  Redistribution and use in source and binary forms, with or without
;;  modification, are permitted provided that the following conditions
;;  are met:
;;
;;  1. Redistributions of source code must retain the above copyright
;;     notice, this list of conditions and the following disclaimer.
;;  2. Redistributions in binary form must reproduce the above copyright
;;     notice, this list of conditions and the following disclaimer in the
;;     documentation and/or other materials provided with the distribution.
;;  3. Neither the name of authors nor the names of its contributors
;;     may be used to endorse or promote products derived from this software
;;     without specific prior written permission.
;;
;;  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS ``AS
;;  IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
;;  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
;;  PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR
;;  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
;;  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
;;  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
;;  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
;;  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
;;  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
;;  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

(load "./test/unittest.scm")

(define tn test-name)

;; char=?
(tn "char=? #\\x00")
(assert-true   (tn) (char=? #\x00 #\x00))
(assert-false  (tn) (char=? #\x00 #\newline))
(assert-false  (tn) (char=? #\x00 #\space))
(assert-false  (tn) (char=? #\x00 #\!))
(assert-false  (tn) (char=? #\x00 #\0))
(assert-false  (tn) (char=? #\x00 #\9))
(assert-false  (tn) (char=? #\x00 #\A))
(assert-false  (tn) (char=? #\x00 #\B))
(assert-false  (tn) (char=? #\x00 #\Z))
(assert-false  (tn) (char=? #\x00 #\a))
(assert-false  (tn) (char=? #\x00 #\b))
(assert-false  (tn) (char=? #\x00 #\z))
(assert-false  (tn) (char=? #\x00 #\~))
(assert-false  (tn) (char=? #\x00 #\x7f))
(tn "char=? #\\newline")
(assert-false  (tn) (char=? #\newline #\x00))
(assert-true   (tn) (char=? #\newline #\newline))
(assert-false  (tn) (char=? #\newline #\space))
(assert-false  (tn) (char=? #\newline #\!))
(assert-false  (tn) (char=? #\newline #\0))
(assert-false  (tn) (char=? #\newline #\9))
(assert-false  (tn) (char=? #\newline #\A))
(assert-false  (tn) (char=? #\newline #\B))
(assert-false  (tn) (char=? #\newline #\Z))
(assert-false  (tn) (char=? #\newline #\a))
(assert-false  (tn) (char=? #\newline #\b))
(assert-false  (tn) (char=? #\newline #\z))
(assert-false  (tn) (char=? #\newline #\~))
(assert-false  (tn) (char=? #\newline #\x7f))
(tn "char=? #\\space")
(assert-false  (tn) (char=? #\space #\x00))
(assert-false  (tn) (char=? #\space #\newline))
(assert-true   (tn) (char=? #\space #\space))
(assert-false  (tn) (char=? #\space #\!))
(assert-false  (tn) (char=? #\space #\0))
(assert-false  (tn) (char=? #\space #\9))
(assert-false  (tn) (char=? #\space #\A))
(assert-false  (tn) (char=? #\space #\B))
(assert-false  (tn) (char=? #\space #\Z))
(assert-false  (tn) (char=? #\space #\a))
(assert-false  (tn) (char=? #\space #\b))
(assert-false  (tn) (char=? #\space #\z))
(assert-false  (tn) (char=? #\space #\~))
(assert-false  (tn) (char=? #\space #\x7f))
(tn "char=? #\\!")
(assert-false  (tn) (char=? #\! #\x00))
(assert-false  (tn) (char=? #\! #\newline))
(assert-false  (tn) (char=? #\! #\space))
(assert-true   (tn) (char=? #\! #\!))
(assert-false  (tn) (char=? #\! #\0))
(assert-false  (tn) (char=? #\! #\9))
(assert-false  (tn) (char=? #\! #\A))
(assert-false  (tn) (char=? #\! #\B))
(assert-false  (tn) (char=? #\! #\Z))
(assert-false  (tn) (char=? #\! #\a))
(assert-false  (tn) (char=? #\! #\b))
(assert-false  (tn) (char=? #\! #\z))
(assert-false  (tn) (char=? #\! #\~))
(assert-false  (tn) (char=? #\! #\x7f))
(tn "char=? #\\0")
(assert-false  (tn) (char=? #\0 #\x00))
(assert-false  (tn) (char=? #\0 #\newline))
(assert-false  (tn) (char=? #\0 #\space))
(assert-false  (tn) (char=? #\0 #\!))
(assert-true   (tn) (char=? #\0 #\0))
(assert-false  (tn) (char=? #\0 #\9))
(assert-false  (tn) (char=? #\0 #\A))
(assert-false  (tn) (char=? #\0 #\B))
(assert-false  (tn) (char=? #\0 #\Z))
(assert-false  (tn) (char=? #\0 #\a))
(assert-false  (tn) (char=? #\0 #\b))
(assert-false  (tn) (char=? #\0 #\z))
(assert-false  (tn) (char=? #\0 #\~))
(assert-false  (tn) (char=? #\0 #\x7f))
(tn "char=? #\\9")
(assert-false  (tn) (char=? #\9 #\x00))
(assert-false  (tn) (char=? #\9 #\newline))
(assert-false  (tn) (char=? #\9 #\space))
(assert-false  (tn) (char=? #\9 #\!))
(assert-false  (tn) (char=? #\9 #\0))
(assert-true   (tn) (char=? #\9 #\9))
(assert-false  (tn) (char=? #\9 #\A))
(assert-false  (tn) (char=? #\9 #\B))
(assert-false  (tn) (char=? #\9 #\Z))
(assert-false  (tn) (char=? #\9 #\a))
(assert-false  (tn) (char=? #\9 #\b))
(assert-false  (tn) (char=? #\9 #\z))
(assert-false  (tn) (char=? #\9 #\~))
(assert-false  (tn) (char=? #\9 #\x7f))
(tn "char=? #\\A")
(assert-false  (tn) (char=? #\A #\x00))
(assert-false  (tn) (char=? #\A #\newline))
(assert-false  (tn) (char=? #\A #\space))
(assert-false  (tn) (char=? #\A #\!))
(assert-false  (tn) (char=? #\A #\0))
(assert-false  (tn) (char=? #\A #\9))
(assert-true   (tn) (char=? #\A #\A))
(assert-false  (tn) (char=? #\A #\B))
(assert-false  (tn) (char=? #\A #\Z))
(assert-false  (tn) (char=? #\A #\a))
(assert-false  (tn) (char=? #\A #\b))
(assert-false  (tn) (char=? #\A #\z))
(assert-false  (tn) (char=? #\A #\~))
(assert-false  (tn) (char=? #\A #\x7f))
(tn "char=? #\\B")
(assert-false  (tn) (char=? #\B #\x00))
(assert-false  (tn) (char=? #\B #\newline))
(assert-false  (tn) (char=? #\B #\space))
(assert-false  (tn) (char=? #\B #\!))
(assert-false  (tn) (char=? #\B #\0))
(assert-false  (tn) (char=? #\B #\9))
(assert-false  (tn) (char=? #\B #\A))
(assert-true   (tn) (char=? #\B #\B))
(assert-false  (tn) (char=? #\B #\Z))
(assert-false  (tn) (char=? #\B #\a))
(assert-false  (tn) (char=? #\B #\b))
(assert-false  (tn) (char=? #\B #\z))
(assert-false  (tn) (char=? #\B #\~))
(assert-false  (tn) (char=? #\B #\x7f))
(tn "char=? #\\Z")
(assert-false  (tn) (char=? #\Z #\x00))
(assert-false  (tn) (char=? #\Z #\newline))
(assert-false  (tn) (char=? #\Z #\space))
(assert-false  (tn) (char=? #\Z #\!))
(assert-false  (tn) (char=? #\Z #\0))
(assert-false  (tn) (char=? #\Z #\9))
(assert-false  (tn) (char=? #\Z #\A))
(assert-false  (tn) (char=? #\Z #\B))
(assert-true   (tn) (char=? #\Z #\Z))
(assert-false  (tn) (char=? #\Z #\a))
(assert-false  (tn) (char=? #\Z #\b))
(assert-false  (tn) (char=? #\Z #\z))
(assert-false  (tn) (char=? #\Z #\~))
(assert-false  (tn) (char=? #\Z #\x7f))
(tn "char=? #\\a")
(assert-false  (tn) (char=? #\a #\x00))
(assert-false  (tn) (char=? #\a #\newline))
(assert-false  (tn) (char=? #\a #\space))
(assert-false  (tn) (char=? #\a #\!))
(assert-false  (tn) (char=? #\a #\0))
(assert-false  (tn) (char=? #\a #\9))
(assert-false  (tn) (char=? #\a #\A))
(assert-false  (tn) (char=? #\a #\B))
(assert-false  (tn) (char=? #\a #\Z))
(assert-true   (tn) (char=? #\a #\a))
(assert-false  (tn) (char=? #\a #\b))
(assert-false  (tn) (char=? #\a #\z))
(assert-false  (tn) (char=? #\a #\~))
(assert-false  (tn) (char=? #\a #\x7f))
(tn "char=? #\\b")
(assert-false  (tn) (char=? #\b #\x00))
(assert-false  (tn) (char=? #\b #\newline))
(assert-false  (tn) (char=? #\b #\space))
(assert-false  (tn) (char=? #\b #\!))
(assert-false  (tn) (char=? #\b #\0))
(assert-false  (tn) (char=? #\b #\9))
(assert-false  (tn) (char=? #\b #\A))
(assert-false  (tn) (char=? #\b #\B))
(assert-false  (tn) (char=? #\b #\Z))
(assert-false  (tn) (char=? #\b #\a))
(assert-true   (tn) (char=? #\b #\b))
(assert-false  (tn) (char=? #\b #\z))
(assert-false  (tn) (char=? #\b #\~))
(assert-false  (tn) (char=? #\b #\x7f))
(tn "char=? #\\z")
(assert-false  (tn) (char=? #\z #\x00))
(assert-false  (tn) (char=? #\z #\newline))
(assert-false  (tn) (char=? #\z #\space))
(assert-false  (tn) (char=? #\z #\!))
(assert-false  (tn) (char=? #\z #\0))
(assert-false  (tn) (char=? #\z #\9))
(assert-false  (tn) (char=? #\z #\A))
(assert-false  (tn) (char=? #\z #\B))
(assert-false  (tn) (char=? #\z #\Z))
(assert-false  (tn) (char=? #\z #\a))
(assert-false  (tn) (char=? #\z #\b))
(assert-true   (tn) (char=? #\z #\z))
(assert-false  (tn) (char=? #\z #\~))
(assert-false  (tn) (char=? #\z #\x7f))
(tn "char=? #\\~")
(assert-false  (tn) (char=? #\~ #\x00))
(assert-false  (tn) (char=? #\~ #\newline))
(assert-false  (tn) (char=? #\~ #\space))
(assert-false  (tn) (char=? #\~ #\!))
(assert-false  (tn) (char=? #\~ #\0))
(assert-false  (tn) (char=? #\~ #\9))
(assert-false  (tn) (char=? #\~ #\A))
(assert-false  (tn) (char=? #\~ #\B))
(assert-false  (tn) (char=? #\~ #\Z))
(assert-false  (tn) (char=? #\~ #\a))
(assert-false  (tn) (char=? #\~ #\b))
(assert-false  (tn) (char=? #\~ #\z))
(assert-true   (tn) (char=? #\~ #\~))
(assert-false  (tn) (char=? #\~ #\x7f))
(tn "char=? #\\x7f")
(assert-false  (tn) (char=? #\x7f #\x00))
(assert-false  (tn) (char=? #\x7f #\newline))
(assert-false  (tn) (char=? #\x7f #\space))
(assert-false  (tn) (char=? #\x7f #\!))
(assert-false  (tn) (char=? #\x7f #\0))
(assert-false  (tn) (char=? #\x7f #\9))
(assert-false  (tn) (char=? #\x7f #\A))
(assert-false  (tn) (char=? #\x7f #\B))
(assert-false  (tn) (char=? #\x7f #\Z))
(assert-false  (tn) (char=? #\x7f #\a))
(assert-false  (tn) (char=? #\x7f #\b))
(assert-false  (tn) (char=? #\x7f #\z))
(assert-false  (tn) (char=? #\x7f #\~))
(assert-true   (tn) (char=? #\x7f #\x7f))

;; char<?
(tn "char<? #\\x00")
(assert-false  (tn) (char<? #\x00 #\x00))
(assert-true   (tn) (char<? #\x00 #\newline))
(assert-true   (tn) (char<? #\x00 #\space))
(assert-true   (tn) (char<? #\x00 #\!))
(assert-true   (tn) (char<? #\x00 #\0))
(assert-true   (tn) (char<? #\x00 #\9))
(assert-true   (tn) (char<? #\x00 #\A))
(assert-true   (tn) (char<? #\x00 #\B))
(assert-true   (tn) (char<? #\x00 #\Z))
(assert-true   (tn) (char<? #\x00 #\a))
(assert-true   (tn) (char<? #\x00 #\b))
(assert-true   (tn) (char<? #\x00 #\z))
(assert-true   (tn) (char<? #\x00 #\~))
(assert-true   (tn) (char<? #\x00 #\x7f))
(tn "char<? #\\newline")
(assert-false  (tn) (char<? #\newline #\x00))
(assert-false  (tn) (char<? #\newline #\newline))
(assert-true   (tn) (char<? #\newline #\space))
(assert-true   (tn) (char<? #\newline #\!))
(assert-true   (tn) (char<? #\newline #\0))
(assert-true   (tn) (char<? #\newline #\9))
(assert-true   (tn) (char<? #\newline #\A))
(assert-true   (tn) (char<? #\newline #\B))
(assert-true   (tn) (char<? #\newline #\Z))
(assert-true   (tn) (char<? #\newline #\a))
(assert-true   (tn) (char<? #\newline #\b))
(assert-true   (tn) (char<? #\newline #\z))
(assert-true   (tn) (char<? #\newline #\~))
(assert-true   (tn) (char<? #\newline #\x7f))
(tn "char<? #\\space")
(assert-false  (tn) (char<? #\space #\x00))
(assert-false  (tn) (char<? #\space #\newline))
(assert-false  (tn) (char<? #\space #\space))
(assert-true   (tn) (char<? #\space #\!))
(assert-true   (tn) (char<? #\space #\0))
(assert-true   (tn) (char<? #\space #\9))
(assert-true   (tn) (char<? #\space #\A))
(assert-true   (tn) (char<? #\space #\B))
(assert-true   (tn) (char<? #\space #\Z))
(assert-true   (tn) (char<? #\space #\a))
(assert-true   (tn) (char<? #\space #\b))
(assert-true   (tn) (char<? #\space #\z))
(assert-true   (tn) (char<? #\space #\~))
(assert-true   (tn) (char<? #\space #\x7f))
(tn "char<? #\\!")
(assert-false  (tn) (char<? #\! #\x00))
(assert-false  (tn) (char<? #\! #\newline))
(assert-false  (tn) (char<? #\! #\space))
(assert-false  (tn) (char<? #\! #\!))
(assert-true   (tn) (char<? #\! #\0))
(assert-true   (tn) (char<? #\! #\9))
(assert-true   (tn) (char<? #\! #\A))
(assert-true   (tn) (char<? #\! #\B))
(assert-true   (tn) (char<? #\! #\Z))
(assert-true   (tn) (char<? #\! #\a))
(assert-true   (tn) (char<? #\! #\b))
(assert-true   (tn) (char<? #\! #\z))
(assert-true   (tn) (char<? #\! #\~))
(assert-true   (tn) (char<? #\! #\x7f))
(tn "char<? #\\0")
(assert-false  (tn) (char<? #\0 #\x00))
(assert-false  (tn) (char<? #\0 #\newline))
(assert-false  (tn) (char<? #\0 #\space))
(assert-false  (tn) (char<? #\0 #\!))
(assert-false  (tn) (char<? #\0 #\0))
(assert-true   (tn) (char<? #\0 #\9))
(assert-true   (tn) (char<? #\0 #\A))
(assert-true   (tn) (char<? #\0 #\B))
(assert-true   (tn) (char<? #\0 #\Z))
(assert-true   (tn) (char<? #\0 #\a))
(assert-true   (tn) (char<? #\0 #\b))
(assert-true   (tn) (char<? #\0 #\z))
(assert-true   (tn) (char<? #\0 #\~))
(assert-true   (tn) (char<? #\0 #\x7f))
(tn "char<? #\\9")
(assert-false  (tn) (char<? #\9 #\x00))
(assert-false  (tn) (char<? #\9 #\newline))
(assert-false  (tn) (char<? #\9 #\space))
(assert-false  (tn) (char<? #\9 #\!))
(assert-false  (tn) (char<? #\9 #\0))
(assert-false  (tn) (char<? #\9 #\9))
(assert-true   (tn) (char<? #\9 #\A))
(assert-true   (tn) (char<? #\9 #\B))
(assert-true   (tn) (char<? #\9 #\Z))
(assert-true   (tn) (char<? #\9 #\a))
(assert-true   (tn) (char<? #\9 #\b))
(assert-true   (tn) (char<? #\9 #\z))
(assert-true   (tn) (char<? #\9 #\~))
(assert-true   (tn) (char<? #\9 #\x7f))
(tn "char<? #\\A")
(assert-false  (tn) (char<? #\A #\x00))
(assert-false  (tn) (char<? #\A #\newline))
(assert-false  (tn) (char<? #\A #\space))
(assert-false  (tn) (char<? #\A #\!))
(assert-false  (tn) (char<? #\A #\0))
(assert-false  (tn) (char<? #\A #\9))
(assert-false  (tn) (char<? #\A #\A))
(assert-true   (tn) (char<? #\A #\B))
(assert-true   (tn) (char<? #\A #\Z))
(assert-true   (tn) (char<? #\A #\a))
(assert-true   (tn) (char<? #\A #\b))
(assert-true   (tn) (char<? #\A #\z))
(assert-true   (tn) (char<? #\A #\~))
(assert-true   (tn) (char<? #\A #\x7f))
(tn "char<? #\\B")
(assert-false  (tn) (char<? #\B #\x00))
(assert-false  (tn) (char<? #\B #\newline))
(assert-false  (tn) (char<? #\B #\space))
(assert-false  (tn) (char<? #\B #\!))
(assert-false  (tn) (char<? #\B #\0))
(assert-false  (tn) (char<? #\B #\9))
(assert-false  (tn) (char<? #\B #\A))
(assert-false  (tn) (char<? #\B #\B))
(assert-true   (tn) (char<? #\B #\Z))
(assert-true   (tn) (char<? #\B #\a))
(assert-true   (tn) (char<? #\B #\b))
(assert-true   (tn) (char<? #\B #\z))
(assert-true   (tn) (char<? #\B #\~))
(assert-true   (tn) (char<? #\B #\x7f))
(tn "char<? #\\Z")
(assert-false  (tn) (char<? #\Z #\x00))
(assert-false  (tn) (char<? #\Z #\newline))
(assert-false  (tn) (char<? #\Z #\space))
(assert-false  (tn) (char<? #\Z #\!))
(assert-false  (tn) (char<? #\Z #\0))
(assert-false  (tn) (char<? #\Z #\9))
(assert-false  (tn) (char<? #\Z #\A))
(assert-false  (tn) (char<? #\Z #\B))
(assert-false  (tn) (char<? #\Z #\Z))
(assert-true   (tn) (char<? #\Z #\a))
(assert-true   (tn) (char<? #\Z #\b))
(assert-true   (tn) (char<? #\Z #\z))
(assert-true   (tn) (char<? #\Z #\~))
(assert-true   (tn) (char<? #\Z #\x7f))
(tn "char<? #\\a")
(assert-false  (tn) (char<? #\a #\x00))
(assert-false  (tn) (char<? #\a #\newline))
(assert-false  (tn) (char<? #\a #\space))
(assert-false  (tn) (char<? #\a #\!))
(assert-false  (tn) (char<? #\a #\0))
(assert-false  (tn) (char<? #\a #\9))
(assert-false  (tn) (char<? #\a #\A))
(assert-false  (tn) (char<? #\a #\B))
(assert-false  (tn) (char<? #\a #\Z))
(assert-false  (tn) (char<? #\a #\a))
(assert-true   (tn) (char<? #\a #\b))
(assert-true   (tn) (char<? #\a #\z))
(assert-true   (tn) (char<? #\a #\~))
(assert-true   (tn) (char<? #\a #\x7f))
(tn "char<? #\\b")
(assert-false  (tn) (char<? #\b #\x00))
(assert-false  (tn) (char<? #\b #\newline))
(assert-false  (tn) (char<? #\b #\space))
(assert-false  (tn) (char<? #\b #\!))
(assert-false  (tn) (char<? #\b #\0))
(assert-false  (tn) (char<? #\b #\9))
(assert-false  (tn) (char<? #\b #\A))
(assert-false  (tn) (char<? #\b #\B))
(assert-false  (tn) (char<? #\b #\Z))
(assert-false  (tn) (char<? #\b #\a))
(assert-false  (tn) (char<? #\b #\b))
(assert-true   (tn) (char<? #\b #\z))
(assert-true   (tn) (char<? #\b #\~))
(assert-true   (tn) (char<? #\b #\x7f))
(tn "char<? #\\z")
(assert-false  (tn) (char<? #\z #\x00))
(assert-false  (tn) (char<? #\z #\newline))
(assert-false  (tn) (char<? #\z #\space))
(assert-false  (tn) (char<? #\z #\!))
(assert-false  (tn) (char<? #\z #\0))
(assert-false  (tn) (char<? #\z #\9))
(assert-false  (tn) (char<? #\z #\A))
(assert-false  (tn) (char<? #\z #\B))
(assert-false  (tn) (char<? #\z #\Z))
(assert-false  (tn) (char<? #\z #\a))
(assert-false  (tn) (char<? #\z #\b))
(assert-false  (tn) (char<? #\z #\z))
(assert-true   (tn) (char<? #\z #\~))
(assert-true   (tn) (char<? #\z #\x7f))
(tn "char<? #\\~")
(assert-false  (tn) (char<? #\~ #\x00))
(assert-false  (tn) (char<? #\~ #\newline))
(assert-false  (tn) (char<? #\~ #\space))
(assert-false  (tn) (char<? #\~ #\!))
(assert-false  (tn) (char<? #\~ #\0))
(assert-false  (tn) (char<? #\~ #\9))
(assert-false  (tn) (char<? #\~ #\A))
(assert-false  (tn) (char<? #\~ #\B))
(assert-false  (tn) (char<? #\~ #\Z))
(assert-false  (tn) (char<? #\~ #\a))
(assert-false  (tn) (char<? #\~ #\b))
(assert-false  (tn) (char<? #\~ #\z))
(assert-false  (tn) (char<? #\~ #\~))
(assert-true   (tn) (char<? #\~ #\x7f))
(tn "char<? #\\x7f")
(assert-false  (tn) (char<? #\x7f #\x00))
(assert-false  (tn) (char<? #\x7f #\newline))
(assert-false  (tn) (char<? #\x7f #\space))
(assert-false  (tn) (char<? #\x7f #\!))
(assert-false  (tn) (char<? #\x7f #\0))
(assert-false  (tn) (char<? #\x7f #\9))
(assert-false  (tn) (char<? #\x7f #\A))
(assert-false  (tn) (char<? #\x7f #\B))
(assert-false  (tn) (char<? #\x7f #\Z))
(assert-false  (tn) (char<? #\x7f #\a))
(assert-false  (tn) (char<? #\x7f #\b))
(assert-false  (tn) (char<? #\x7f #\z))
(assert-false  (tn) (char<? #\x7f #\~))
(assert-false  (tn) (char<? #\x7f #\x7f))

;; char>?
(tn "char>? #\\x00")
(assert-false  (tn) (char>? #\x00 #\x00))
(assert-false  (tn) (char>? #\x00 #\newline))
(assert-false  (tn) (char>? #\x00 #\space))
(assert-false  (tn) (char>? #\x00 #\!))
(assert-false  (tn) (char>? #\x00 #\0))
(assert-false  (tn) (char>? #\x00 #\9))
(assert-false  (tn) (char>? #\x00 #\A))
(assert-false  (tn) (char>? #\x00 #\B))
(assert-false  (tn) (char>? #\x00 #\Z))
(assert-false  (tn) (char>? #\x00 #\a))
(assert-false  (tn) (char>? #\x00 #\b))
(assert-false  (tn) (char>? #\x00 #\z))
(assert-false  (tn) (char>? #\x00 #\~))
(assert-false  (tn) (char>? #\x00 #\x7f))
(tn "char>? #\\newline")
(assert-true   (tn) (char>? #\newline #\x00))
(assert-false  (tn) (char>? #\newline #\newline))
(assert-false  (tn) (char>? #\newline #\space))
(assert-false  (tn) (char>? #\newline #\!))
(assert-false  (tn) (char>? #\newline #\0))
(assert-false  (tn) (char>? #\newline #\9))
(assert-false  (tn) (char>? #\newline #\A))
(assert-false  (tn) (char>? #\newline #\B))
(assert-false  (tn) (char>? #\newline #\Z))
(assert-false  (tn) (char>? #\newline #\a))
(assert-false  (tn) (char>? #\newline #\b))
(assert-false  (tn) (char>? #\newline #\z))
(assert-false  (tn) (char>? #\newline #\~))
(assert-false  (tn) (char>? #\newline #\x7f))
(tn "char>? #\\space")
(assert-true   (tn) (char>? #\space #\x00))
(assert-true   (tn) (char>? #\space #\newline))
(assert-false  (tn) (char>? #\space #\space))
(assert-false  (tn) (char>? #\space #\!))
(assert-false  (tn) (char>? #\space #\0))
(assert-false  (tn) (char>? #\space #\9))
(assert-false  (tn) (char>? #\space #\A))
(assert-false  (tn) (char>? #\space #\B))
(assert-false  (tn) (char>? #\space #\Z))
(assert-false  (tn) (char>? #\space #\a))
(assert-false  (tn) (char>? #\space #\b))
(assert-false  (tn) (char>? #\space #\z))
(assert-false  (tn) (char>? #\space #\~))
(assert-false  (tn) (char>? #\space #\x7f))
(tn "char>? #\\!")
(assert-true   (tn) (char>? #\! #\x00))
(assert-true   (tn) (char>? #\! #\newline))
(assert-true   (tn) (char>? #\! #\space))
(assert-false  (tn) (char>? #\! #\!))
(assert-false  (tn) (char>? #\! #\0))
(assert-false  (tn) (char>? #\! #\9))
(assert-false  (tn) (char>? #\! #\A))
(assert-false  (tn) (char>? #\! #\B))
(assert-false  (tn) (char>? #\! #\Z))
(assert-false  (tn) (char>? #\! #\a))
(assert-false  (tn) (char>? #\! #\b))
(assert-false  (tn) (char>? #\! #\z))
(assert-false  (tn) (char>? #\! #\~))
(assert-false  (tn) (char>? #\! #\x7f))
(tn "char>? #\\0")
(assert-true   (tn) (char>? #\0 #\x00))
(assert-true   (tn) (char>? #\0 #\newline))
(assert-true   (tn) (char>? #\0 #\space))
(assert-true   (tn) (char>? #\0 #\!))
(assert-false  (tn) (char>? #\0 #\0))
(assert-false  (tn) (char>? #\0 #\9))
(assert-false  (tn) (char>? #\0 #\A))
(assert-false  (tn) (char>? #\0 #\B))
(assert-false  (tn) (char>? #\0 #\Z))
(assert-false  (tn) (char>? #\0 #\a))
(assert-false  (tn) (char>? #\0 #\b))
(assert-false  (tn) (char>? #\0 #\z))
(assert-false  (tn) (char>? #\0 #\~))
(assert-false  (tn) (char>? #\0 #\x7f))
(tn "char>? #\\9")
(assert-true   (tn) (char>? #\9 #\x00))
(assert-true   (tn) (char>? #\9 #\newline))
(assert-true   (tn) (char>? #\9 #\space))
(assert-true   (tn) (char>? #\9 #\!))
(assert-true   (tn) (char>? #\9 #\0))
(assert-false  (tn) (char>? #\9 #\9))
(assert-false  (tn) (char>? #\9 #\A))
(assert-false  (tn) (char>? #\9 #\B))
(assert-false  (tn) (char>? #\9 #\Z))
(assert-false  (tn) (char>? #\9 #\a))
(assert-false  (tn) (char>? #\9 #\b))
(assert-false  (tn) (char>? #\9 #\z))
(assert-false  (tn) (char>? #\9 #\~))
(assert-false  (tn) (char>? #\9 #\x7f))
(tn "char>? #\\A")
(assert-true   (tn) (char>? #\A #\x00))
(assert-true   (tn) (char>? #\A #\newline))
(assert-true   (tn) (char>? #\A #\space))
(assert-true   (tn) (char>? #\A #\!))
(assert-true   (tn) (char>? #\A #\0))
(assert-true   (tn) (char>? #\A #\9))
(assert-false  (tn) (char>? #\A #\A))
(assert-false  (tn) (char>? #\A #\B))
(assert-false  (tn) (char>? #\A #\Z))
(assert-false  (tn) (char>? #\A #\a))
(assert-false  (tn) (char>? #\A #\b))
(assert-false  (tn) (char>? #\A #\z))
(assert-false  (tn) (char>? #\A #\~))
(assert-false  (tn) (char>? #\A #\x7f))
(tn "char>? #\\B")
(assert-true   (tn) (char>? #\B #\x00))
(assert-true   (tn) (char>? #\B #\newline))
(assert-true   (tn) (char>? #\B #\space))
(assert-true   (tn) (char>? #\B #\!))
(assert-true   (tn) (char>? #\B #\0))
(assert-true   (tn) (char>? #\B #\9))
(assert-true   (tn) (char>? #\B #\A))
(assert-false  (tn) (char>? #\B #\B))
(assert-false  (tn) (char>? #\B #\Z))
(assert-false  (tn) (char>? #\B #\a))
(assert-false  (tn) (char>? #\B #\b))
(assert-false  (tn) (char>? #\B #\z))
(assert-false  (tn) (char>? #\B #\~))
(assert-false  (tn) (char>? #\B #\x7f))
(tn "char>? #\\Z")
(assert-true   (tn) (char>? #\Z #\x00))
(assert-true   (tn) (char>? #\Z #\newline))
(assert-true   (tn) (char>? #\Z #\space))
(assert-true   (tn) (char>? #\Z #\!))
(assert-true   (tn) (char>? #\Z #\0))
(assert-true   (tn) (char>? #\Z #\9))
(assert-true   (tn) (char>? #\Z #\A))
(assert-true   (tn) (char>? #\Z #\B))
(assert-false  (tn) (char>? #\Z #\Z))
(assert-false  (tn) (char>? #\Z #\a))
(assert-false  (tn) (char>? #\Z #\b))
(assert-false  (tn) (char>? #\Z #\z))
(assert-false  (tn) (char>? #\Z #\~))
(assert-false  (tn) (char>? #\Z #\x7f))
(tn "char>? #\\a")
(assert-true   (tn) (char>? #\a #\x00))
(assert-true   (tn) (char>? #\a #\newline))
(assert-true   (tn) (char>? #\a #\space))
(assert-true   (tn) (char>? #\a #\!))
(assert-true   (tn) (char>? #\a #\0))
(assert-true   (tn) (char>? #\a #\9))
(assert-true   (tn) (char>? #\a #\A))
(assert-true   (tn) (char>? #\a #\B))
(assert-true   (tn) (char>? #\a #\Z))
(assert-false  (tn) (char>? #\a #\a))
(assert-false  (tn) (char>? #\a #\b))
(assert-false  (tn) (char>? #\a #\z))
(assert-false  (tn) (char>? #\a #\~))
(assert-false  (tn) (char>? #\a #\x7f))
(tn "char>? #\\b")
(assert-true   (tn) (char>? #\b #\x00))
(assert-true   (tn) (char>? #\b #\newline))
(assert-true   (tn) (char>? #\b #\space))
(assert-true   (tn) (char>? #\b #\!))
(assert-true   (tn) (char>? #\b #\0))
(assert-true   (tn) (char>? #\b #\9))
(assert-true   (tn) (char>? #\b #\A))
(assert-true   (tn) (char>? #\b #\B))
(assert-true   (tn) (char>? #\b #\Z))
(assert-true   (tn) (char>? #\b #\a))
(assert-false  (tn) (char>? #\b #\b))
(assert-false  (tn) (char>? #\b #\z))
(assert-false  (tn) (char>? #\b #\~))
(assert-false  (tn) (char>? #\b #\x7f))
(tn "char>? #\\z")
(assert-true   (tn) (char>? #\z #\x00))
(assert-true   (tn) (char>? #\z #\newline))
(assert-true   (tn) (char>? #\z #\space))
(assert-true   (tn) (char>? #\z #\!))
(assert-true   (tn) (char>? #\z #\0))
(assert-true   (tn) (char>? #\z #\9))
(assert-true   (tn) (char>? #\z #\A))
(assert-true   (tn) (char>? #\z #\B))
(assert-true   (tn) (char>? #\z #\Z))
(assert-true   (tn) (char>? #\z #\a))
(assert-true   (tn) (char>? #\z #\b))
(assert-false  (tn) (char>? #\z #\z))
(assert-false  (tn) (char>? #\z #\~))
(assert-false  (tn) (char>? #\z #\x7f))
(tn "char>? #\\~")
(assert-true   (tn) (char>? #\~ #\x00))
(assert-true   (tn) (char>? #\~ #\newline))
(assert-true   (tn) (char>? #\~ #\space))
(assert-true   (tn) (char>? #\~ #\!))
(assert-true   (tn) (char>? #\~ #\0))
(assert-true   (tn) (char>? #\~ #\9))
(assert-true   (tn) (char>? #\~ #\A))
(assert-true   (tn) (char>? #\~ #\B))
(assert-true   (tn) (char>? #\~ #\Z))
(assert-true   (tn) (char>? #\~ #\a))
(assert-true   (tn) (char>? #\~ #\b))
(assert-true   (tn) (char>? #\~ #\z))
(assert-false  (tn) (char>? #\~ #\~))
(assert-false  (tn) (char>? #\~ #\x7f))
(tn "char>? #\\x7f")
(assert-true   (tn) (char>? #\x7f #\x00))
(assert-true   (tn) (char>? #\x7f #\newline))
(assert-true   (tn) (char>? #\x7f #\space))
(assert-true   (tn) (char>? #\x7f #\!))
(assert-true   (tn) (char>? #\x7f #\0))
(assert-true   (tn) (char>? #\x7f #\9))
(assert-true   (tn) (char>? #\x7f #\A))
(assert-true   (tn) (char>? #\x7f #\B))
(assert-true   (tn) (char>? #\x7f #\Z))
(assert-true   (tn) (char>? #\x7f #\a))
(assert-true   (tn) (char>? #\x7f #\b))
(assert-true   (tn) (char>? #\x7f #\z))
(assert-true   (tn) (char>? #\x7f #\~))
(assert-false  (tn) (char>? #\x7f #\x7f))

;; char<=?
(tn "char<=? #\\x00")
(assert-true   (tn) (char<=? #\x00 #\x00))
(assert-true   (tn) (char<=? #\x00 #\newline))
(assert-true   (tn) (char<=? #\x00 #\space))
(assert-true   (tn) (char<=? #\x00 #\!))
(assert-true   (tn) (char<=? #\x00 #\0))
(assert-true   (tn) (char<=? #\x00 #\9))
(assert-true   (tn) (char<=? #\x00 #\A))
(assert-true   (tn) (char<=? #\x00 #\B))
(assert-true   (tn) (char<=? #\x00 #\Z))
(assert-true   (tn) (char<=? #\x00 #\a))
(assert-true   (tn) (char<=? #\x00 #\b))
(assert-true   (tn) (char<=? #\x00 #\z))
(assert-true   (tn) (char<=? #\x00 #\~))
(assert-true   (tn) (char<=? #\x00 #\x7f))
(tn "char<=? #\\newline")
(assert-false  (tn) (char<=? #\newline #\x00))
(assert-true   (tn) (char<=? #\newline #\newline))
(assert-true   (tn) (char<=? #\newline #\space))
(assert-true   (tn) (char<=? #\newline #\!))
(assert-true   (tn) (char<=? #\newline #\0))
(assert-true   (tn) (char<=? #\newline #\9))
(assert-true   (tn) (char<=? #\newline #\A))
(assert-true   (tn) (char<=? #\newline #\B))
(assert-true   (tn) (char<=? #\newline #\Z))
(assert-true   (tn) (char<=? #\newline #\a))
(assert-true   (tn) (char<=? #\newline #\b))
(assert-true   (tn) (char<=? #\newline #\z))
(assert-true   (tn) (char<=? #\newline #\~))
(assert-true   (tn) (char<=? #\newline #\x7f))
(tn "char<=? #\\space")
(assert-false  (tn) (char<=? #\space #\x00))
(assert-false  (tn) (char<=? #\space #\newline))
(assert-true   (tn) (char<=? #\space #\space))
(assert-true   (tn) (char<=? #\space #\!))
(assert-true   (tn) (char<=? #\space #\0))
(assert-true   (tn) (char<=? #\space #\9))
(assert-true   (tn) (char<=? #\space #\A))
(assert-true   (tn) (char<=? #\space #\B))
(assert-true   (tn) (char<=? #\space #\Z))
(assert-true   (tn) (char<=? #\space #\a))
(assert-true   (tn) (char<=? #\space #\b))
(assert-true   (tn) (char<=? #\space #\z))
(assert-true   (tn) (char<=? #\space #\~))
(assert-true   (tn) (char<=? #\space #\x7f))
(tn "char<=? #\\!")
(assert-false  (tn) (char<=? #\! #\x00))
(assert-false  (tn) (char<=? #\! #\newline))
(assert-false  (tn) (char<=? #\! #\space))
(assert-true   (tn) (char<=? #\! #\!))
(assert-true   (tn) (char<=? #\! #\0))
(assert-true   (tn) (char<=? #\! #\9))
(assert-true   (tn) (char<=? #\! #\A))
(assert-true   (tn) (char<=? #\! #\B))
(assert-true   (tn) (char<=? #\! #\Z))
(assert-true   (tn) (char<=? #\! #\a))
(assert-true   (tn) (char<=? #\! #\b))
(assert-true   (tn) (char<=? #\! #\z))
(assert-true   (tn) (char<=? #\! #\~))
(assert-true   (tn) (char<=? #\! #\x7f))
(tn "char<=? #\\0")
(assert-false  (tn) (char<=? #\0 #\x00))
(assert-false  (tn) (char<=? #\0 #\newline))
(assert-false  (tn) (char<=? #\0 #\space))
(assert-false  (tn) (char<=? #\0 #\!))
(assert-true   (tn) (char<=? #\0 #\0))
(assert-true   (tn) (char<=? #\0 #\9))
(assert-true   (tn) (char<=? #\0 #\A))
(assert-true   (tn) (char<=? #\0 #\B))
(assert-true   (tn) (char<=? #\0 #\Z))
(assert-true   (tn) (char<=? #\0 #\a))
(assert-true   (tn) (char<=? #\0 #\b))
(assert-true   (tn) (char<=? #\0 #\z))
(assert-true   (tn) (char<=? #\0 #\~))
(assert-true   (tn) (char<=? #\0 #\x7f))
(tn "char<=? #\\9")
(assert-false  (tn) (char<=? #\9 #\x00))
(assert-false  (tn) (char<=? #\9 #\newline))
(assert-false  (tn) (char<=? #\9 #\space))
(assert-false  (tn) (char<=? #\9 #\!))
(assert-false  (tn) (char<=? #\9 #\0))
(assert-true   (tn) (char<=? #\9 #\9))
(assert-true   (tn) (char<=? #\9 #\A))
(assert-true   (tn) (char<=? #\9 #\B))
(assert-true   (tn) (char<=? #\9 #\Z))
(assert-true   (tn) (char<=? #\9 #\a))
(assert-true   (tn) (char<=? #\9 #\b))
(assert-true   (tn) (char<=? #\9 #\z))
(assert-true   (tn) (char<=? #\9 #\~))
(assert-true   (tn) (char<=? #\9 #\x7f))
(tn "char<=? #\\A")
(assert-false  (tn) (char<=? #\A #\x00))
(assert-false  (tn) (char<=? #\A #\newline))
(assert-false  (tn) (char<=? #\A #\space))
(assert-false  (tn) (char<=? #\A #\!))
(assert-false  (tn) (char<=? #\A #\0))
(assert-false  (tn) (char<=? #\A #\9))
(assert-true   (tn) (char<=? #\A #\A))
(assert-true   (tn) (char<=? #\A #\B))
(assert-true   (tn) (char<=? #\A #\Z))
(assert-true   (tn) (char<=? #\A #\a))
(assert-true   (tn) (char<=? #\A #\b))
(assert-true   (tn) (char<=? #\A #\z))
(assert-true   (tn) (char<=? #\A #\~))
(assert-true   (tn) (char<=? #\A #\x7f))
(tn "char<=? #\\B")
(assert-false  (tn) (char<=? #\B #\x00))
(assert-false  (tn) (char<=? #\B #\newline))
(assert-false  (tn) (char<=? #\B #\space))
(assert-false  (tn) (char<=? #\B #\!))
(assert-false  (tn) (char<=? #\B #\0))
(assert-false  (tn) (char<=? #\B #\9))
(assert-false  (tn) (char<=? #\B #\A))
(assert-true   (tn) (char<=? #\B #\B))
(assert-true   (tn) (char<=? #\B #\Z))
(assert-true   (tn) (char<=? #\B #\a))
(assert-true   (tn) (char<=? #\B #\b))
(assert-true   (tn) (char<=? #\B #\z))
(assert-true   (tn) (char<=? #\B #\~))
(assert-true   (tn) (char<=? #\B #\x7f))
(tn "char<=? #\\Z")
(assert-false  (tn) (char<=? #\Z #\x00))
(assert-false  (tn) (char<=? #\Z #\newline))
(assert-false  (tn) (char<=? #\Z #\space))
(assert-false  (tn) (char<=? #\Z #\!))
(assert-false  (tn) (char<=? #\Z #\0))
(assert-false  (tn) (char<=? #\Z #\9))
(assert-false  (tn) (char<=? #\Z #\A))
(assert-false  (tn) (char<=? #\Z #\B))
(assert-true   (tn) (char<=? #\Z #\Z))
(assert-true   (tn) (char<=? #\Z #\a))
(assert-true   (tn) (char<=? #\Z #\b))
(assert-true   (tn) (char<=? #\Z #\z))
(assert-true   (tn) (char<=? #\Z #\~))
(assert-true   (tn) (char<=? #\Z #\x7f))
(tn "char<=? #\\a")
(assert-false  (tn) (char<=? #\a #\x00))
(assert-false  (tn) (char<=? #\a #\newline))
(assert-false  (tn) (char<=? #\a #\space))
(assert-false  (tn) (char<=? #\a #\!))
(assert-false  (tn) (char<=? #\a #\0))
(assert-false  (tn) (char<=? #\a #\9))
(assert-false  (tn) (char<=? #\a #\A))
(assert-false  (tn) (char<=? #\a #\B))
(assert-false  (tn) (char<=? #\a #\Z))
(assert-true   (tn) (char<=? #\a #\a))
(assert-true   (tn) (char<=? #\a #\b))
(assert-true   (tn) (char<=? #\a #\z))
(assert-true   (tn) (char<=? #\a #\~))
(assert-true   (tn) (char<=? #\a #\x7f))
(tn "char<=? #\\b")
(assert-false  (tn) (char<=? #\b #\x00))
(assert-false  (tn) (char<=? #\b #\newline))
(assert-false  (tn) (char<=? #\b #\space))
(assert-false  (tn) (char<=? #\b #\!))
(assert-false  (tn) (char<=? #\b #\0))
(assert-false  (tn) (char<=? #\b #\9))
(assert-false  (tn) (char<=? #\b #\A))
(assert-false  (tn) (char<=? #\b #\B))
(assert-false  (tn) (char<=? #\b #\Z))
(assert-false  (tn) (char<=? #\b #\a))
(assert-true   (tn) (char<=? #\b #\b))
(assert-true   (tn) (char<=? #\b #\z))
(assert-true   (tn) (char<=? #\b #\~))
(assert-true   (tn) (char<=? #\b #\x7f))
(tn "char<=? #\\z")
(assert-false  (tn) (char<=? #\z #\x00))
(assert-false  (tn) (char<=? #\z #\newline))
(assert-false  (tn) (char<=? #\z #\space))
(assert-false  (tn) (char<=? #\z #\!))
(assert-false  (tn) (char<=? #\z #\0))
(assert-false  (tn) (char<=? #\z #\9))
(assert-false  (tn) (char<=? #\z #\A))
(assert-false  (tn) (char<=? #\z #\B))
(assert-false  (tn) (char<=? #\z #\Z))
(assert-false  (tn) (char<=? #\z #\a))
(assert-false  (tn) (char<=? #\z #\b))
(assert-true   (tn) (char<=? #\z #\z))
(assert-true   (tn) (char<=? #\z #\~))
(assert-true   (tn) (char<=? #\z #\x7f))
(tn "char<=? #\\~")
(assert-false  (tn) (char<=? #\~ #\x00))
(assert-false  (tn) (char<=? #\~ #\newline))
(assert-false  (tn) (char<=? #\~ #\space))
(assert-false  (tn) (char<=? #\~ #\!))
(assert-false  (tn) (char<=? #\~ #\0))
(assert-false  (tn) (char<=? #\~ #\9))
(assert-false  (tn) (char<=? #\~ #\A))
(assert-false  (tn) (char<=? #\~ #\B))
(assert-false  (tn) (char<=? #\~ #\Z))
(assert-false  (tn) (char<=? #\~ #\a))
(assert-false  (tn) (char<=? #\~ #\b))
(assert-false  (tn) (char<=? #\~ #\z))
(assert-true   (tn) (char<=? #\~ #\~))
(assert-true   (tn) (char<=? #\~ #\x7f))
(tn "char<=? #\\x7f")
(assert-false  (tn) (char<=? #\x7f #\x00))
(assert-false  (tn) (char<=? #\x7f #\newline))
(assert-false  (tn) (char<=? #\x7f #\space))
(assert-false  (tn) (char<=? #\x7f #\!))
(assert-false  (tn) (char<=? #\x7f #\0))
(assert-false  (tn) (char<=? #\x7f #\9))
(assert-false  (tn) (char<=? #\x7f #\A))
(assert-false  (tn) (char<=? #\x7f #\B))
(assert-false  (tn) (char<=? #\x7f #\Z))
(assert-false  (tn) (char<=? #\x7f #\a))
(assert-false  (tn) (char<=? #\x7f #\b))
(assert-false  (tn) (char<=? #\x7f #\z))
(assert-false  (tn) (char<=? #\x7f #\~))
(assert-true   (tn) (char<=? #\x7f #\x7f))

;; char>=?
(tn "char>=? #\\x00")
(assert-true   (tn) (char>=? #\x00 #\x00))
(assert-false  (tn) (char>=? #\x00 #\newline))
(assert-false  (tn) (char>=? #\x00 #\space))
(assert-false  (tn) (char>=? #\x00 #\!))
(assert-false  (tn) (char>=? #\x00 #\0))
(assert-false  (tn) (char>=? #\x00 #\9))
(assert-false  (tn) (char>=? #\x00 #\A))
(assert-false  (tn) (char>=? #\x00 #\B))
(assert-false  (tn) (char>=? #\x00 #\Z))
(assert-false  (tn) (char>=? #\x00 #\a))
(assert-false  (tn) (char>=? #\x00 #\b))
(assert-false  (tn) (char>=? #\x00 #\z))
(assert-false  (tn) (char>=? #\x00 #\~))
(assert-false  (tn) (char>=? #\x00 #\x7f))
(tn "char>=? #\\newline")
(assert-true   (tn) (char>=? #\newline #\x00))
(assert-true   (tn) (char>=? #\newline #\newline))
(assert-false  (tn) (char>=? #\newline #\space))
(assert-false  (tn) (char>=? #\newline #\!))
(assert-false  (tn) (char>=? #\newline #\0))
(assert-false  (tn) (char>=? #\newline #\9))
(assert-false  (tn) (char>=? #\newline #\A))
(assert-false  (tn) (char>=? #\newline #\B))
(assert-false  (tn) (char>=? #\newline #\Z))
(assert-false  (tn) (char>=? #\newline #\a))
(assert-false  (tn) (char>=? #\newline #\b))
(assert-false  (tn) (char>=? #\newline #\z))
(assert-false  (tn) (char>=? #\newline #\~))
(assert-false  (tn) (char>=? #\newline #\x7f))
(tn "char>=? #\\space")
(assert-true   (tn) (char>=? #\space #\x00))
(assert-true   (tn) (char>=? #\space #\newline))
(assert-true   (tn) (char>=? #\space #\space))
(assert-false  (tn) (char>=? #\space #\!))
(assert-false  (tn) (char>=? #\space #\0))
(assert-false  (tn) (char>=? #\space #\9))
(assert-false  (tn) (char>=? #\space #\A))
(assert-false  (tn) (char>=? #\space #\B))
(assert-false  (tn) (char>=? #\space #\Z))
(assert-false  (tn) (char>=? #\space #\a))
(assert-false  (tn) (char>=? #\space #\b))
(assert-false  (tn) (char>=? #\space #\z))
(assert-false  (tn) (char>=? #\space #\~))
(assert-false  (tn) (char>=? #\space #\x7f))
(tn "char>=? #\\!")
(assert-true   (tn) (char>=? #\! #\x00))
(assert-true   (tn) (char>=? #\! #\newline))
(assert-true   (tn) (char>=? #\! #\space))
(assert-true   (tn) (char>=? #\! #\!))
(assert-false  (tn) (char>=? #\! #\0))
(assert-false  (tn) (char>=? #\! #\9))
(assert-false  (tn) (char>=? #\! #\A))
(assert-false  (tn) (char>=? #\! #\B))
(assert-false  (tn) (char>=? #\! #\Z))
(assert-false  (tn) (char>=? #\! #\a))
(assert-false  (tn) (char>=? #\! #\b))
(assert-false  (tn) (char>=? #\! #\z))
(assert-false  (tn) (char>=? #\! #\~))
(assert-false  (tn) (char>=? #\! #\x7f))
(tn "char>=? #\\0")
(assert-true   (tn) (char>=? #\0 #\x00))
(assert-true   (tn) (char>=? #\0 #\newline))
(assert-true   (tn) (char>=? #\0 #\space))
(assert-true   (tn) (char>=? #\0 #\!))
(assert-true   (tn) (char>=? #\0 #\0))
(assert-false  (tn) (char>=? #\0 #\9))
(assert-false  (tn) (char>=? #\0 #\A))
(assert-false  (tn) (char>=? #\0 #\B))
(assert-false  (tn) (char>=? #\0 #\Z))
(assert-false  (tn) (char>=? #\0 #\a))
(assert-false  (tn) (char>=? #\0 #\b))
(assert-false  (tn) (char>=? #\0 #\z))
(assert-false  (tn) (char>=? #\0 #\~))
(assert-false  (tn) (char>=? #\0 #\x7f))
(tn "char>=? #\\9")
(assert-true   (tn) (char>=? #\9 #\x00))
(assert-true   (tn) (char>=? #\9 #\newline))
(assert-true   (tn) (char>=? #\9 #\space))
(assert-true   (tn) (char>=? #\9 #\!))
(assert-true   (tn) (char>=? #\9 #\0))
(assert-true   (tn) (char>=? #\9 #\9))
(assert-false  (tn) (char>=? #\9 #\A))
(assert-false  (tn) (char>=? #\9 #\B))
(assert-false  (tn) (char>=? #\9 #\Z))
(assert-false  (tn) (char>=? #\9 #\a))
(assert-false  (tn) (char>=? #\9 #\b))
(assert-false  (tn) (char>=? #\9 #\z))
(assert-false  (tn) (char>=? #\9 #\~))
(assert-false  (tn) (char>=? #\9 #\x7f))
(tn "char>=? #\\A")
(assert-true   (tn) (char>=? #\A #\x00))
(assert-true   (tn) (char>=? #\A #\newline))
(assert-true   (tn) (char>=? #\A #\space))
(assert-true   (tn) (char>=? #\A #\!))
(assert-true   (tn) (char>=? #\A #\0))
(assert-true   (tn) (char>=? #\A #\9))
(assert-true   (tn) (char>=? #\A #\A))
(assert-false  (tn) (char>=? #\A #\B))
(assert-false  (tn) (char>=? #\A #\Z))
(assert-false  (tn) (char>=? #\A #\a))
(assert-false  (tn) (char>=? #\A #\b))
(assert-false  (tn) (char>=? #\A #\z))
(assert-false  (tn) (char>=? #\A #\~))
(assert-false  (tn) (char>=? #\A #\x7f))
(tn "char>=? #\\B")
(assert-true   (tn) (char>=? #\B #\x00))
(assert-true   (tn) (char>=? #\B #\newline))
(assert-true   (tn) (char>=? #\B #\space))
(assert-true   (tn) (char>=? #\B #\!))
(assert-true   (tn) (char>=? #\B #\0))
(assert-true   (tn) (char>=? #\B #\9))
(assert-true   (tn) (char>=? #\B #\A))
(assert-true   (tn) (char>=? #\B #\B))
(assert-false  (tn) (char>=? #\B #\Z))
(assert-false  (tn) (char>=? #\B #\a))
(assert-false  (tn) (char>=? #\B #\b))
(assert-false  (tn) (char>=? #\B #\z))
(assert-false  (tn) (char>=? #\B #\~))
(assert-false  (tn) (char>=? #\B #\x7f))
(tn "char>=? #\\Z")
(assert-true   (tn) (char>=? #\Z #\x00))
(assert-true   (tn) (char>=? #\Z #\newline))
(assert-true   (tn) (char>=? #\Z #\space))
(assert-true   (tn) (char>=? #\Z #\!))
(assert-true   (tn) (char>=? #\Z #\0))
(assert-true   (tn) (char>=? #\Z #\9))
(assert-true   (tn) (char>=? #\Z #\A))
(assert-true   (tn) (char>=? #\Z #\B))
(assert-true   (tn) (char>=? #\Z #\Z))
(assert-false  (tn) (char>=? #\Z #\a))
(assert-false  (tn) (char>=? #\Z #\b))
(assert-false  (tn) (char>=? #\Z #\z))
(assert-false  (tn) (char>=? #\Z #\~))
(assert-false  (tn) (char>=? #\Z #\x7f))
(tn "char>=? #\\a")
(assert-true   (tn) (char>=? #\a #\x00))
(assert-true   (tn) (char>=? #\a #\newline))
(assert-true   (tn) (char>=? #\a #\space))
(assert-true   (tn) (char>=? #\a #\!))
(assert-true   (tn) (char>=? #\a #\0))
(assert-true   (tn) (char>=? #\a #\9))
(assert-true   (tn) (char>=? #\a #\A))
(assert-true   (tn) (char>=? #\a #\B))
(assert-true   (tn) (char>=? #\a #\Z))
(assert-true   (tn) (char>=? #\a #\a))
(assert-false  (tn) (char>=? #\a #\b))
(assert-false  (tn) (char>=? #\a #\z))
(assert-false  (tn) (char>=? #\a #\~))
(assert-false  (tn) (char>=? #\a #\x7f))
(tn "char>=? #\\b")
(assert-true   (tn) (char>=? #\b #\x00))
(assert-true   (tn) (char>=? #\b #\newline))
(assert-true   (tn) (char>=? #\b #\space))
(assert-true   (tn) (char>=? #\b #\!))
(assert-true   (tn) (char>=? #\b #\0))
(assert-true   (tn) (char>=? #\b #\9))
(assert-true   (tn) (char>=? #\b #\A))
(assert-true   (tn) (char>=? #\b #\B))
(assert-true   (tn) (char>=? #\b #\Z))
(assert-true   (tn) (char>=? #\b #\a))
(assert-true   (tn) (char>=? #\b #\b))
(assert-false  (tn) (char>=? #\b #\z))
(assert-false  (tn) (char>=? #\b #\~))
(assert-false  (tn) (char>=? #\b #\x7f))
(tn "char>=? #\\z")
(assert-true   (tn) (char>=? #\z #\x00))
(assert-true   (tn) (char>=? #\z #\newline))
(assert-true   (tn) (char>=? #\z #\space))
(assert-true   (tn) (char>=? #\z #\!))
(assert-true   (tn) (char>=? #\z #\0))
(assert-true   (tn) (char>=? #\z #\9))
(assert-true   (tn) (char>=? #\z #\A))
(assert-true   (tn) (char>=? #\z #\B))
(assert-true   (tn) (char>=? #\z #\Z))
(assert-true   (tn) (char>=? #\z #\a))
(assert-true   (tn) (char>=? #\z #\b))
(assert-true   (tn) (char>=? #\z #\z))
(assert-false  (tn) (char>=? #\z #\~))
(assert-false  (tn) (char>=? #\z #\x7f))
(tn "char>=? #\\~")
(assert-true   (tn) (char>=? #\~ #\x00))
(assert-true   (tn) (char>=? #\~ #\newline))
(assert-true   (tn) (char>=? #\~ #\space))
(assert-true   (tn) (char>=? #\~ #\!))
(assert-true   (tn) (char>=? #\~ #\0))
(assert-true   (tn) (char>=? #\~ #\9))
(assert-true   (tn) (char>=? #\~ #\A))
(assert-true   (tn) (char>=? #\~ #\B))
(assert-true   (tn) (char>=? #\~ #\Z))
(assert-true   (tn) (char>=? #\~ #\a))
(assert-true   (tn) (char>=? #\~ #\b))
(assert-true   (tn) (char>=? #\~ #\z))
(assert-true   (tn) (char>=? #\~ #\~))
(assert-false  (tn) (char>=? #\~ #\x7f))
(tn "char>=? #\\x7f")
(assert-true   (tn) (char>=? #\x7f #\x00))
(assert-true   (tn) (char>=? #\x7f #\newline))
(assert-true   (tn) (char>=? #\x7f #\space))
(assert-true   (tn) (char>=? #\x7f #\!))
(assert-true   (tn) (char>=? #\x7f #\0))
(assert-true   (tn) (char>=? #\x7f #\9))
(assert-true   (tn) (char>=? #\x7f #\A))
(assert-true   (tn) (char>=? #\x7f #\B))
(assert-true   (tn) (char>=? #\x7f #\Z))
(assert-true   (tn) (char>=? #\x7f #\a))
(assert-true   (tn) (char>=? #\x7f #\b))
(assert-true   (tn) (char>=? #\x7f #\z))
(assert-true   (tn) (char>=? #\x7f #\~))
(assert-true   (tn) (char>=? #\x7f #\x7f))

(total-report)
