(load "./test/unittest.scm")

; and-let*
(assert-true  "and-let* test 1" (and-let* () #t))
(assert-true  "and-let* test 2" (and-let* () #t #t))
(assert-true  "and-let* test 3" (and-let* () #t #t #t))
(assert-false "and-let* test 4" (and-let* () #f))
(assert-false "and-let* test 5" (and-let* () #t #f))
(assert-false "and-let* test 6" (and-let* () #t #t #f))
(assert-false "and-let* test 7" (and-let* ((false (< 2 1)))
                                          #t))
(assert-false "and-let* test 8" (and-let* ((true  (< 1 2))
                                           (false (< 2 1)))
                                          #t))
(assert-true  "and-let* test 9" (and-let* ((one 1)
                                           (two (+ one 1))
                                           (three (+ two 1)))
                                          (= three 3)))
(assert-false "and-let* test 10" (and-let* ((one 1)
                                            (two (+ one 1))
                                            (three (+ two 1)))
                                           (= three 4)))

(total-report)
