######################################################################
# Automatically generated by qmake (1.08a) Tue Aug 24 01:02:27 2004
######################################################################

TEMPLATE = app
CONFIG -= moc
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += qt warn_on debug

QMAKE_STRIP =

# Input
SOURCES += main.cpp
